# Generated by Django 5.0.6 on 2025-03-05 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("organizations", "0008_organizationsstatisticcategories_color"),
        ("tags", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="people_in_charge",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="responsible_person",
        ),
        migrations.AddField(
            model_name="tag",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OrganizationsTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_tags",
                        to="companies.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_tags",
                        to="organizations.organization",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_tags",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="organizations",
            field=models.ManyToManyField(
                related_name="tags",
                through="tags.OrganizationsTags",
                to="organizations.organization",
            ),
        ),
        migrations.DeleteModel(
            name="PeopleInChargeTags",
        ),
    ]
