# Generated by Django 5.0.6 on 2025-11-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_remove_tag_people_in_charge_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="is_hidden",
        ),
    ]
