steps:
  # Get ENV from SecretManager and write to .env
  - id: "Write ENV"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    secretEnv: ["_SYSTEM_ENV"]
    args: ["-c", 'echo "$$_SYSTEM_ENV" > officedock-system/.env']

  # Build Docker Image on Cloud Build
  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv: ["_SYSTEM_ARTIFACT_REGISTRY_PATH"]
    args:
      [
        "-c",
        "docker build --platform linux/amd64 -t $$_SYSTEM_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA -f Dockerfile.production .",
      ]
    dir: "officedock-system"

  # Push built Docker Image on Artifact Registry
  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv: ["_SYSTEM_ARTIFACT_REGISTRY_PATH"]
    args: ["-c", "docker push $$_SYSTEM_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA"]

  # Deploy built Docker Image on Cloud Run
  - id: "Deploy Docker Image"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    secretEnv:
      [
        "_SYSTEM_ARTIFACT_REGISTRY_PATH",
        "_SYSTEM_REGION",
        "_SYSTEM_SERVICE_NAME",
      ]
    args:
      - "-c"
      - |
        set -eux

        # Replace dot with hyphen. (e.g. v1.0.0 -> v1-0-0)
        NORMALIZED_TAG_NAME="$(echo "$TAG_NAME" | sed 's/\./-/g')"

        gcloud run deploy $$_SYSTEM_SERVICE_NAME \
          --image $$_SYSTEM_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
          --region $$_SYSTEM_REGION \
          --tag "$$NORMALIZED_TAG_NAME" \
          --service-account $_CR_SERVICE_ACCOUNT \
          --port 3000 \
          --network $_NETWORK \
          --subnet $_CR_EGRESS_SUBNET \
          --ingress $_CR_INGRESS  \
          --vpc-egress $_CR_VPC_EGRESS \
          --allow-unauthenticated \
          --cpu=$_CR_CPU \
          --memory=$_CR_MEMORY \
          --concurrency $_CR_CONCURRENCY \
          --min $_CR_MIN_INSTANCES \
          --min-instances 0 \
          --max-instances $_CR_MAX_INSTANCES

options:
  logging: CLOUD_LOGGING_ONLY

# Please configure these substitutions in Cloud Build trigger.
substitutions:
  # They should match the name of VPC and subnet
  _NETWORK:
  _CR_EGRESS_SUBNET:
  _CR_SERVICE_ACCOUNT:

  # Cloud Run settings
  _CR_INGRESS: internal-and-cloud-load-balancing # all / internal / internal-and-cloud-load-balancing
  _CR_VPC_EGRESS: all-traffic # all / all-traffic / private-ranges-only
  _CR_CPU: "1"
  _CR_MEMORY: "512Mi"
  _CR_CONCURRENCY: "50"
  _CR_MIN_INSTANCES: "0" # "0" means cold start
  _CR_MAX_INSTANCES: "50"
# Settings SecretManager
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_SYSTEM_ARTIFACT_REGISTRY_PATH/versions/latest
      env: _SYSTEM_ARTIFACT_REGISTRY_PATH
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_SYSTEM_REGION/versions/latest
      env: _SYSTEM_REGION
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_SYSTEM_SERVICE_NAME/versions/latest
      env: _SYSTEM_SERVICE_NAME
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_SYSTEM_ENV/versions/latest
      env: _SYSTEM_ENV
