steps:
  # Build Docker Image on Cloud Build
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['_SYSTEM_ARTIFACT_REGISTRY_PATH', '_BUILD_ENV']
    args:
    - "-c"
    - |
      # Extract value from .env format
      extract_env() {
        echo "$$_BUILD_ENV" | grep "^$1=" | cut -d '=' -f2-
      }

      docker build --platform linux/amd64 \
        --build-arg NEXT_PUBLIC_API_URL="$$(extract_env NEXT_PUBLIC_API_URL)" \
        --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="$$(extract_env NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY)" \
        --build-arg NEXT_PUBLIC_HELP_PAGE_URL="$$(extract_env NEXT_PUBLIC_HELP_PAGE_URL)" \
        --build-arg API_INTERNAL_URL="$$(extract_env API_INTERNAL_URL)" \
        --build-arg RUNTIME_ENV_PATH=$_RUNTIME_ENV_PATH \
        -t $$_SYSTEM_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
        -f Dockerfile.staging .

  # Push built Docker Image on Artifact Registry
  - id: 'Push Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['_SYSTEM_ARTIFACT_REGISTRY_PATH']
    args: ['-c', 'docker push $$_SYSTEM_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA']

  # Deploy built Docker Image on Cloud Run
  - id: 'Deploy Docker Image'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv:
      [
        '_SYSTEM_ARTIFACT_REGISTRY_PATH',
        '_SYSTEM_REGION',
        '_SYSTEM_SERVICE_NAME',
      ]
    args: [
        '-c',
        "gcloud run deploy $$_SYSTEM_SERVICE_NAME \
        --image $$_SYSTEM_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
        --region $$_SYSTEM_REGION \
        --port 3000 \
        --allow-unauthenticated \
        --update-secrets=$_RUNTIME_ENV_PATH=$_SECRET_ENV_NAME:latest",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Secret Manager settings
  _SECRET_ENV_NAME: STG_SYSTEM_ENV
  _RUNTIME_ENV_PATH: /secrets/.env

# Settings SecretManager
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_SYSTEM_ARTIFACT_REGISTRY_PATH/versions/latest
      env: _SYSTEM_ARTIFACT_REGISTRY_PATH
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_SYSTEM_REGION/versions/latest
      env: _SYSTEM_REGION
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_SYSTEM_SERVICE_NAME/versions/latest
      env: _SYSTEM_SERVICE_NAME
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_SYSTEM_ENV/versions/latest
      env: _BUILD_ENV
