steps:
  # Build Docker Image on Cloud Build
  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv: ["_API_ARTIFACT_REGISTRY_PATH"]
    args:
      [
        "-c",
        "docker build --platform linux/amd64 -t $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA -f Dockerfile.production .",
      ]
    dir: "officedock-api"

  # Push built Docker Image on Artifact Registry
  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv: ["_API_ARTIFACT_REGISTRY_PATH"]
    args: ["-c", "docker push $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA"]

  - id: "Create Database Backup"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - "-c"
      - >
        set -eux

        CLOUD_SQL_INSTANCE_NAME=$(echo "$$_API_CLOUD_SQL_INSTANCE" | sed 's/^[^:]*:[^:]*://')

        gcloud sql backups create --instance="$$CLOUD_SQL_INSTANCE_NAME"
        --description "TAG: $TAG_NAME, COMMIT_SHA: $COMMIT_SHA"

        echo "Database backup completed successfully."
    entrypoint: bash
    secretEnv: ["_API_CLOUD_SQL_INSTANCE"]

  # Deploy SQL migrate job
  - id: "Deploy migrate job"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: [
        "-c",
        "gcloud run jobs deploy migrate-job \
        --image $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
        --region $$_API_REGION \
        --service-account $_CR_SERVICE_ACCOUNT \
        --set-cloudsql-instances $$_API_CLOUD_SQL_INSTANCE \
        --set-env-vars SECRET_PREFIX=PROD \
        --max-retries 1 \
        --network $_NETWORK \
        --subnet $_CR_EGRESS_SUBNET \
        --vpc-egress private-ranges-only \
        --command 'bash' \
        --args '/code/migrate-production.sh' \
        --execute-now \
        --wait",
      ]
    secretEnv:
      ["_API_ARTIFACT_REGISTRY_PATH", "_API_REGION", "_API_CLOUD_SQL_INSTANCE"]

    # Deploy built Docker Image on Cloud Run
  - id: "Deploy Docker Image"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    secretEnv:
      [
        "_API_ARTIFACT_REGISTRY_PATH",
        "_API_REGION",
        "_API_SERVICE_NAME",
        "_API_CLOUD_SQL_INSTANCE",
      ]
    args:
      - "-c"
      - |
        set -eux

        # Replace dot with hyphen. (e.g. v1.0.0 -> v1-0-0)
        NORMALIZED_TAG_NAME="$(echo "$TAG_NAME" | sed 's/\./-/g')"

        gcloud run deploy $$_API_SERVICE_NAME \
          --image $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
          --region $$_API_REGION \
          --tag "$$NORMALIZED_TAG_NAME" \
          --port 8080 \
          --service-account $_CR_SERVICE_ACCOUNT \
          --network $_NETWORK \
          --subnet $_CR_EGRESS_SUBNET \
          --ingress $_CR_INGRESS \
          --vpc-egress $_CR_VPC_EGRESS \
          --add-cloudsql-instances $$_API_CLOUD_SQL_INSTANCE \
          --set-env-vars SECRET_PREFIX=PROD,WORKERS_COUNT=$_GUNICORN_WORKERS_COUNT,THREADS_COUNT=$_GUNICORN_THREADS_COUNT \
          $_CR_ALLOW_AUTHENTICATED \
          --cpu=$_CR_CPU \
          --memory=$_CR_MEMORY \
          --concurrency $_CR_CONCURRENCY \
          --min-instances $_CR_MIN_INSTANCES \
          --max-instances $_CR_MAX_INSTANCES

options:
  logging: CLOUD_LOGGING_ONLY

# Please configure these substitutions in Cloud Build trigger.
substitutions:
  # They should match the name of VPC and subnet
  _NETWORK:
  _CR_EGRESS_SUBNET:
  _CR_SERVICE_ACCOUNT:

  # Cloud Run settings
  _CR_INGRESS: internal # all / internal / internal-and-cloud-load-balancing
  _CR_VPC_EGRESS: all-traffic # all / all-traffic / private-ranges-only
  _CR_ALLOW_AUTHENTICATED: --allow-unauthenticated # --[no]-allow-unauthenticated
  _CR_CPU: "1"
  _CR_MEMORY: "512Mi"
  _CR_CONCURRENCY: "50"
  _CR_MIN_INSTANCES: "0" # "0" means cold start
  _CR_MAX_INSTANCES: "50"
  # Django settings
  _GUNICORN_WORKERS_COUNT: "1"
  _GUNICORN_THREADS_COUNT: "8"

# Setting SecretManger
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_API_ARTIFACT_REGISTRY_PATH/versions/latest
      env: _API_ARTIFACT_REGISTRY_PATH
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_API_REGION/versions/latest
      env: _API_REGION
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_API_SERVICE_NAME/versions/latest
      env: _API_SERVICE_NAME
    - versionName: projects/${PROJECT_NUMBER}/secrets/PROD_API_CLOUD_SQL_INSTANCE/versions/latest
      env: _API_CLOUD_SQL_INSTANCE
