steps:
  # Build Docker Image on Cloud Build
  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv: ["_API_ARTIFACT_REGISTRY_PATH"]
    args:
      [
        "-c",
        "docker build --platform linux/amd64 -t $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA -f Dockerfile.staging .",
      ]
    dir: "officedock-api"

  # Push built Docker Image on Artifact Registry
  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv: ["_API_ARTIFACT_REGISTRY_PATH"]
    args: ["-c", "docker push $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA"]

  # Deploy SQL migrate job
  - id: "Deploy migrate job"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: [
        "-c",
        "gcloud run jobs deploy migrate-job \
        --image $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
        --region $$_API_REGION \
        --set-cloudsql-instances $$_API_CLOUD_SQL_INSTANCE \
        --set-env-vars SECRET_PREFIX=STG \
        --max-retries 1 \
        --command 'bash' \
        --args '/code/migrate-staging.sh' \
        --execute-now \
        --wait",
      ]
    entrypoint: bash
    secretEnv:
      ["_API_ARTIFACT_REGISTRY_PATH", "_API_REGION", "_API_CLOUD_SQL_INSTANCE"]

  # Create cron jobs using Cloud Scheduler
  - id: "Create Cloud Scheduler Jobs"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    secretEnv: ["_API_REGION", "_API_ENV"]
    args:
      - "-c"
      - |
          # Install jq (JSON processor)
          apt-get update && apt-get install -y jq

          # Extract values from the ENV environment variable
          cloud_service_url=$(echo "$$_API_ENV" | grep '^CLOUD_RUN_SERVICE_URL=' | cut -d '=' -f2-)
          secret_key=$(echo "$$_API_ENV" | grep '^SECRET_KEY_FOR_CRONJOB=' | cut -d '=' -f2-)

          # Read jobs from cronjobs.json
          jobs=$(cat cronjobs.json)

          # Process each job
          echo "$jobs" | jq -c '.[]' | while read -r job; do
            # Extract job details from JSON
            job_name=$(echo "$job" | jq -r '.name')
            schedule=$(echo "$job" | jq -r '.schedule')
            timezone=$(echo "$job" | jq -r '.timezone')
            job_uri=$(echo "$job" | jq -r '.uri')

            # Construct the full URL for the Cloud Scheduler job
            cronjob_url="${cloud_service_url}${job_uri}${secret_key}"

            # Check if the job already exists in Cloud Scheduler
            gcloud scheduler jobs describe "$job_name" --location="$$_API_REGION" >/dev/null 2>&1 &&
              action="update" || action="create"

            # Create or update the Cloud Scheduler job
            gcloud scheduler jobs $action http "$job_name" \
              --location="$$_API_REGION" \
              --schedule "$schedule" \
              --uri "$cronjob_url" \
              --time-zone "$timezone"
          done
    dir: "officedock-api"

  # Deploy built Docker Image on Cloud Run
  - id: "Deploy Docker Image"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    secretEnv:
      [
        "_API_ARTIFACT_REGISTRY_PATH",
        "_API_REGION",
        "_API_SERVICE_NAME",
        "_API_CLOUD_SQL_INSTANCE",
      ]
    args: [
        "-c",
        "gcloud run deploy $$_API_SERVICE_NAME \
        --image $$_API_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
        --region $$_API_REGION \
        --port 8080 \
        --add-cloudsql-instances $$_API_CLOUD_SQL_INSTANCE \
        --set-env-vars SECRET_PREFIX=STG,WORKERS_COUNT=$_GUNICORN_WORKERS_COUNT,THREADS_COUNT=$_GUNICORN_THREADS_COUNT \
        --allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

# Please configure these substitutions in Cloud Build trigger.
substitutions:
  _GUNICORN_WORKERS_COUNT: "1"
  _GUNICORN_THREADS_COUNT: "8"

# Setting SecretManger
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_API_ARTIFACT_REGISTRY_PATH/versions/latest
      env: _API_ARTIFACT_REGISTRY_PATH
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_API_REGION/versions/latest
      env: _API_REGION
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_API_SERVICE_NAME/versions/latest
      env: _API_SERVICE_NAME
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_API_CLOUD_SQL_INSTANCE/versions/latest
      env: _API_CLOUD_SQL_INSTANCE
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_API_ENV/versions/latest
      env: _API_ENV
