FROM python:3.10

ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code

ADD requirements.txt /code/

# Install the required packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ADD . /code/
RUN chmod +x /code/entrypoint-staging.sh
RUN chmod +x /code/migrate-staging.sh
ENTRYPOINT ["/code/entrypoint-staging.sh"]
