"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import contextlib
import io
import os
from datetime import timedelta

import environ
import google.auth
from urllib.parse import urlparse
from google.cloud import secretmanager
from pathlib import Path
from redis import SSLConnection


env = environ.Env(DEBUG=(bool, False))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


with contextlib.suppress(google.auth.exceptions.DefaultCredentialsError):
    GOOGLE_CLOUD_CREDENTIALS, GOOGLE_CLOUD_PROJECT_ID = google.auth.default()
    if GOOGLE_CLOUD_PROJECT_ID is not None:
        os.environ["GOOGLE_CLOUD_PROJECT_ID"] = GOOGLE_CLOUD_PROJECT_ID

if GOOGLE_CLOUD_PROJECT_ID := os.environ.get("GOOGLE_CLOUD_PROJECT_ID", None):
    # Pull secrets from Secret Manager
    client = secretmanager.SecretManagerServiceClient()
    SECRET_PREFIX = os.environ.get("SECRET_PREFIX", "")
    name = f"projects/{GOOGLE_CLOUD_PROJECT_ID}/secrets/{SECRET_PREFIX}_API_ENV/versions/latest"
    payload = client.access_secret_version(name=name).payload.data.decode(
        "UTF-8"
    )

    env.read_env(io.StringIO(payload))

    SECRET_KEY = env("SECRET_KEY")
    SYSTEM_WEBAPP_URL = os.getenv("SYSTEM_WEBAPP_URL", "http://localhost:3000")
    ADMIN_WEBAPP_URL = os.getenv("ADMIN_WEBAPP_URL", "http://localhost:3000")
    CLOUD_RUN_SERVICE_URL = env("CLOUD_RUN_SERVICE_URL", default=None)
    ALLOWED_HOSTS = [urlparse(CLOUD_RUN_SERVICE_URL).netloc]
    CSRF_TRUSTED_ORIGINS = [SYSTEM_WEBAPP_URL, ADMIN_WEBAPP_URL]
    CORS_ALLOWED_ORIGINS = [SYSTEM_WEBAPP_URL, ADMIN_WEBAPP_URL]

    DEBUG = env("DEBUG", default=False)
    DATABASES = {"default": env.db()}

    # Config google cloud storage
    # https://django-storages.readthedocs.io/en/latest/backends/gcloud.html

    GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME", None)
    GS_EXPIRATION = 60  # Expires in 60 seconds
    GS_CREDENTIALS = GOOGLE_CLOUD_CREDENTIALS
    GS_QUERYSTRING_AUTH = True
    GS_DEFAULT_ACL = None
    GS_FILE_OVERWRITE = False
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {},
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
    }

    # Config generate gcs signed url with hmac key
    GS_HMAC_ACCESS_ID = os.getenv("GS_HMAC_ACCESS_ID")
    GS_HMAC_SECRET = os.getenv("GS_HMAC_SECRET")
    GS_CUSTOM_ENDPOINT = os.getenv("GS_CUSTOM_ENDPOINT", None)
else:
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = os.getenv("SECRET_KEY")

    SYSTEM_WEBAPP_URL = os.getenv("SYSTEM_WEBAPP_URL", "http://localhost:3000")
    ADMIN_WEBAPP_URL = os.getenv("ADMIN_WEBAPP_URL", "http://localhost:3000")
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = [SYSTEM_WEBAPP_URL, ADMIN_WEBAPP_URL]
    ALLOWED_HOSTS = ["*"]

    # Database
    # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = os.getenv("DEBUG", True)

# Application definition

INSTALLED_APPS = [
    "daphne",  # Daphne ASGI application server
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Swagger
    "drf_spectacular",
    # Service external
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "storages",
    # Add application
    "core",
    "base",
    "common",
    "users",
    "companies",
    "organizations",
    "tags",
    "tasks",
    "dashboard",
    "chat",
    "skills",
    "calendars",
    "terms",
    "stat_data",
    "submit_levels",
    "roles",
    "statistics",
    "surveys",
    "tweets",
    "thanks_messages",
    "mvp_votes",
    "shop_items",
    "dotmoney",
    "plans",
]

# Define constants
DOTMONEY_ACCESS_KEY = os.getenv("DOTMONEY_ACCESS_KEY")
DOTMONEY_SECRET_KEY = os.getenv("DOTMONEY_SECRET_KEY")
DOTMONEY_PRODUCT_ID = os.getenv("DOTMONEY_PRODUCT_ID")
DOTMONEY_BASE_API = os.getenv("DOTMONEY_BASE_API")
DOTMONEY_BASE_URL = os.getenv("DOTMONEY_BASE_URL")
DOTMONEY_VERSION = os.getenv("DOTMONEY_VERSION", "Version1")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", None)
SECRET_KEY_FOR_CRONJOB = os.getenv("SECRET_KEY_FOR_CRONJOB", None)
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD")
MONTHLY_QUOTA_THANKS_MESSAGES = int(
    os.getenv("MONTHLY_QUOTA_THANKS_MESSAGES", 5)
)
THANKS_MESSAGE_SOFT_DELETE_RETENTION_DAYS = int(
    os.getenv("THANKS_MESSAGE_SOFT_DELETE_RETENTION_DAYS", 30)
)
CLOSING_DATE = int(os.getenv("CLOSING_DATE", 31))
EDITABLE_AFTER_CLOSING = int(os.getenv("EDITABLE_AFTER_CLOSING", 10))

# Get REDIS_URL from environment variable or install directly
REDIS_URL = os.getenv("REDIS_URL", None)

# Channels
ASGI_APPLICATION = "core.asgi.application"

if REDIS_URL:
    redis_config = {"address": REDIS_URL}

    ca_data = os.getenv("REDIS_CA_CERTS", None)
    if ca_data:
        redis_config["connection_class"] = SSLConnection
        redis_config["ssl_ca_data"] = ca_data.replace("\\n", "\n")

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
            "CONFIG": {
                "hosts": [redis_config],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# SMTP
# https://docs.djangoproject.com/en/5.0/topics/email/

EMAIL_HOST = os.getenv("EMAIL_HOST", None)
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "") != "false"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", None)
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", None)
EMAIL_SENDER = os.getenv("EMAIL_SENDER", EMAIL_HOST_USER)
NAME_SENDER = os.getenv("NAME_SENDER", "OFFICE DOCK")

if not EMAIL_HOST:
    # Only use in local environment if EMAIL_HOST is not set
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "media/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User model
AUTH_USER_MODEL = "users.User"


# Django REST framework
# https://www.django-rest-framework.org/api-guide/settings/

DEFAULT_RENDERER_CLASSES = (
    "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
)

if DEBUG and not GOOGLE_CLOUD_PROJECT_ID:
    DEFAULT_RENDERER_CLASSES += (
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    )

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": DEFAULT_RENDERER_CLASSES,
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
    "DEFAULT_PAGINATION_CLASS": "base.paginations.BasePagination",
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
}

# Spectacular swagger
# https://drf-spectacular.readthedocs.io/en/latest/settings.html

SPECTACULAR_SETTINGS = {
    "TITLE": "Office Dock API",
    "DESCRIPTION": "The Office Dock use Python, Django, DRF and development with Docker Compose.",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "PARSER_WHITELIST": [
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields"
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "filter": True,
        "persistAuthorization": True,
        "displayRequestDuration": True,
        "tagsSorter": "alpha",
    },
    # Use Basic Authentication to protect the swagger API.
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAuthenticated"],
    "SERVE_AUTHENTICATION": ["base.authentication.SwaggerBasicAuthentication"],
}
