# Generated by Django 5.0.6 on 2024-11-14 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendars", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SELF", "SELF"),
                            ("PRIVATE", "PRIVATE"),
                            ("GROUP", "GROUP"),
                            ("TASK", "TASK"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatRoomsParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("unread_messages", models.IntegerField(default=0)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("pin_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("message", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "MESSAGE"),
                            ("CREATION_TASK", "CREATION_TASK"),
                            ("EDIT_TASK", "EDIT_TASK"),
                            ("ADD_MEMBER_TASK", "ADD_MEMBER_TASK"),
                            ("REMOVE_MEMBER_TASK", "REMOVE_MEMBER_TASK"),
                            ("CREATION_SCHEDULE", "CREATION_SCHEDULE"),
                            ("EDIT_SCHEDULE", "EDIT_SCHEDULE"),
                            ("REMOVE_SCHEDULE", "REMOVE_SCHEDULE"),
                        ],
                        default="MESSAGE",
                        max_length=100,
                    ),
                ),
                ("schedule_changes", models.JSONField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="companies.company",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="calendars.schedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
