# Generated by Django 5.0.6 on 2024-12-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
        ("submit_levels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="submit_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages",
                to="submit_levels.submitlevelhistory",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "MESSAGE"),
                    ("CREATION_TASK", "CREATION_TASK"),
                    ("EDIT_TASK", "EDIT_TASK"),
                    ("SUBMIT_LEVEL_SKILL", "SUBMIT_LEVEL_SKILL"),
                    ("ADD_MEMBER_TASK", "ADD_MEMBER_TASK"),
                    ("REMOVE_MEMBER_TASK", "REMOVE_MEMBER_TASK"),
                    ("CREATION_SCHEDULE", "CREATION_SCHEDULE"),
                    ("EDIT_SCHEDULE", "EDIT_SCHEDULE"),
                    ("REMOVE_SCHEDULE", "REMOVE_SCHEDULE"),
                ],
                default="MESSAGE",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF", "SELF"),
                    ("PRIVATE", "PRIVATE"),
                    ("GROUP", "GROUP"),
                    ("TASK", "TASK"),
                    ("SKILL", "SKILL"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
