# Generated by Django 5.0.6 on 2025-01-24 11:23

from django.db import migrations

from chat.constants import ChatRoomTypes


def remove_duplicate_chat_room(apps, schema_editor):
    """
    Remove duplicate chat room type task and skill, keeping the one with the smallest ID.
    """
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        # Handle TASK type rooms
        task_rooms = user.chat_rooms.filter(type=ChatRoomTypes.TASK.value)
        if task_rooms.count() > 1:
            min_task_id = task_rooms.order_by("id").first().id
            # Delete all duplicate rooms except the one with the smallest ID
            task_rooms.exclude(id=min_task_id).delete()

        # Handle SKILL type rooms
        skill_rooms = user.chat_rooms.filter(type=ChatRoomTypes.SKILL.value)
        if skill_rooms.count() > 1:
            min_skill_id = skill_rooms.order_by("id").first().id
            # Delete all duplicate rooms except the one with the smallest ID
            skill_rooms.exclude(id=min_skill_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0003_chatmessage_submit_level_alter_chatmessage_type_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_chat_room, migrations.RunPython.noop
        ),
    ]
