# Generated by Django 5.0.6 on 2025-02-10 12:47

from django.db import migrations, models

from chat.constants import ROOM_TYPES
from common.utils import generate_unique_code


def seed_data_notify_chat_room(apps, schema_editor):
    """
    Remove duplicate chat room type task and skill, keeping the one with the smallest ID.
    """
    User = apps.get_model("users", "User")
    chat_room = apps.get_model("chat", "ChatRoom")

    for user in User.objects.all():
        for room_type, room_name in ROOM_TYPES:
            code = generate_unique_code(chat_room, "code", 10)
            room = user.chat_rooms.filter(type=room_type.value).first()
            obj, created = chat_room.objects.update_or_create(
                id=room.id if room else None,  # Ensure id is correctly assigned
                defaults={
                    "type": room_type.value,
                    "name": room_name.value,
                    "company": user.company,
                    "code": code
                    if not room
                    else room.code,  # Preserve code on update
                },
            )
            if created:
                obj.participants.add(
                    user, through_defaults={"company": user.company}
                )


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_seed_data_notify_chat_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF", "SELF"),
                    ("PRIVATE", "PRIVATE"),
                    ("GROUP", "GROUP"),
                    ("TASK", "TASK"),
                    ("SKILL", "SKILL"),
                    ("CALENDAR", "CALENDAR"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.RunPython(
            seed_data_notify_chat_room, migrations.RunPython.noop
        ),
    ]
