# Generated by Django 5.0.6 on 2025-02-17 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatroom_update_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="mentioned_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
