# Generated by Django 5.0.6 on 2025-02-18 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatmessage_mentions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="bookmark_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="mentions",
            field=models.ManyToManyField(
                related_name="mentioned_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
