# Generated by Django 5.0.6 on 2025-02-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_chatmessage_bookmark_at_alter_chatmessage_mentions"),
        ("tasks", "0009_task_remind_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="tasks",
            field=models.ManyToManyField(
                related_name="link_messages", to="tasks.task"
            ),
        ),
    ]
