# Generated by Django 5.0.6 on 2025-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chatmessage_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
