# Generated by Django 5.0.6 on 2025-02-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_chatroom_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="quote",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_message",
                to="chat.chatmessage",
            ),
        ),
    ]
