# Generated by Django 5.0.6 on 2025-02-21 10:30

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_reaction"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "original_file",
                    models.FileField(
                        upload_to=chat.models.chat_file_upload_path
                    ),
                ),
                (
                    "compressed_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=chat.models.chat_file_upload_path,
                    ),
                ),
                ("file_type", models.CharField(max_length=255)),
                ("file_size", models.FloatField()),
                (
                    "chat_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_files",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_files",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_files",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
