# Generated by Django 5.0.6 on 2025-02-24 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_unique_uuid(apps, schema_editor):
    ChatFile = apps.get_model("chat", "ChatFile")
    for task in ChatFile.objects.all():
        task.uuid = uuid.uuid4()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_chatfile"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="bookmark_at",
        ),
        migrations.AddField(
            model_name="chatfile",
            name="uuid",
            field=models.UUIDField(unique=True, null=True),
        ),
        migrations.RunPython(
            generate_unique_uuid, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="chatfile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("bookmark_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="bookmark_users",
            field=models.ManyToManyField(
                related_name="bookmark_messages",
                through="chat.Bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
