# Generated by Django 5.0.6 on 2025-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_remove_chatmessage_bookmark_at_chatfile_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "MESSAGE"),
                    ("CREATION_TASK", "CREATION_TASK"),
                    ("EDIT_TASK", "EDIT_TASK"),
                    ("SUBMIT_LEVEL_SKILL", "SUBMIT_LEVEL_SKILL"),
                    ("CREATE_SUBMIT_LEVEL_SKILL", "CREATE_SUBMIT_LEVEL_SKILL"),
                    ("ADD_MEMBER_TASK", "ADD_MEMBER_TASK"),
                    ("REMOVE_MEMBER_TASK", "REMOVE_MEMBER_TASK"),
                    ("CREATION_SCHEDULE", "CREATION_SCHEDULE"),
                    ("EDIT_SCHEDULE", "EDIT_SCHEDULE"),
                    ("REMOVE_SCHEDULE", "REMOVE_SCHEDULE"),
                ],
                default="MESSAGE",
                max_length=100,
            ),
        ),
    ]
