# Generated by Django 5.0.6 on 2025-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_chatmessage_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file_uuid", models.UUIDField()),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=255)),
                ("file_size", models.FloatField()),
                ("chunk_index", models.IntegerField()),
                ("total_chunks", models.IntegerField()),
                ("chunk_file", models.FileField(upload_to="chunks")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
