# Generated by Django 5.0.6 on 2025-07-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_chunkfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="select_organizations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatroomsparticipants",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
    ]
