# Generated by Django 5.0.6 on 2025-07-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_chatroom_select_organizations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroomsparticipants",
            name="hidden_at",
        ),
    ]
