# Generated by Django 5.0.6 on 2025-07-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_remove_chatroomsparticipants_hidden_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatfile",
            name="chat_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_files",
                to="chat.chatmessage",
            ),
        ),
    ]
