# Generated by Django 5.0.6 on 2025-08-01 19:04

import django.db.models.deletion
from django.db import migrations, models


def seed_data_for_task_message(apps, schema_editor):
    """
    Handle seed data
    """
    ChatMessage = apps.get_model("chat", "ChatMessage")
    for chat in ChatMessage.objects.filter(task__isnull=False).all():
        organization = chat.task.organization
        if not organization:
            continue
        chat.organization = organization
        chat.schedule_changes = {
            "task": {
                "id": chat.task.id,
                "title": chat.task.title,
            },
        }
        chat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_alter_chatfile_chat_message"),
        ("organizations", "0017_seed_default_organization_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "MESSAGE"),
                    ("CREATION_TASK", "CREATION_TASK"),
                    ("EDIT_TASK", "EDIT_TASK"),
                    ("SUBMIT_LEVEL_SKILL", "SUBMIT_LEVEL_SKILL"),
                    ("CREATE_SUBMIT_LEVEL_SKILL", "CREATE_SUBMIT_LEVEL_SKILL"),
                    ("ADD_MEMBER_TASK", "ADD_MEMBER_TASK"),
                    ("REMOVE_MEMBER_TASK", "REMOVE_MEMBER_TASK"),
                    ("CREATION_SCHEDULE", "CREATION_SCHEDULE"),
                    ("EDIT_SCHEDULE", "EDIT_SCHEDULE"),
                    ("REMOVE_SCHEDULE", "REMOVE_SCHEDULE"),
                    ("REMOVE_TASK", "REMOVE_TASK"),
                ],
                default="MESSAGE",
                max_length=100,
            ),
        ),
        migrations.RunPython(
            seed_data_for_task_message, migrations.RunPython.noop
        ),
    ]
