# Generated by Django 5.0.6 on 2025-10-02 12:10

import django.db.models.deletion
from django.db import migrations, models


def move_chat_message_to_new_table(apps, schema_editor):
    ChatFile = apps.get_model("chat", "ChatFile")
    for chat_file in ChatFile.objects.all():
        if chat_file.chat_message_id:  # ensure it exists
            chat_file.chat_messages.add(chat_file.chat_message_id)


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_chatmessage_organization_alter_chatmessage_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFileChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_file_chat_messages",
                        to="chat.chatfile",
                    ),
                ),
                (
                    "chat_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_file_chat_messages",
                        to="chat.chatmessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatfile",
            name="chat_messages",
            field=models.ManyToManyField(
                related_name="chat_files",
                through="chat.ChatFileChatMessage",
                to="chat.chatmessage",
            ),
        ),
        migrations.RunPython(
            move_chat_message_to_new_table, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="chatfile",
            name="chat_message",
        ),
    ]
