# Generated by Django 5.0.6 on 2025-10-16 18:06

import django.core.validators
from django.db import migrations, models
from users.constants import AvatarColors


def seed_avatar_color_to_chatrooms(apps, schema_editor):
    """
    Seed icon color to organizations.
    """
    ChatRoom = apps.get_model("chat", "ChatRoom")
    for chatroom in ChatRoom.objects.all():
        chatroom.avatar_color = AvatarColors.random()
        chatroom.save(update_fields=["avatar_color"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0021_remove_chatfile_chat_message_chatfilechatmessage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="chats/avatars",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="avatar_color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            seed_avatar_color_to_chatrooms, migrations.RunPython.noop
        ),
    ]
