# Generated by Django 5.1.15 on 2026-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_chatroom_avatar_chatroom_avatar_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "MESSAGE"),
                    ("CREATION_TASK", "CREATION_TASK"),
                    ("EDIT_TASK", "EDIT_TASK"),
                    ("SUBMIT_LEVEL_SKILL", "SUBMIT_LEVEL_SKILL"),
                    ("CREATE_SUBMIT_LEVEL_SKILL", "CREATE_SUBMIT_LEVEL_SKILL"),
                    ("ADD_MEMBER_TASK", "ADD_MEMBER_TASK"),
                    ("REMOVE_MEMBER_TASK", "REMOVE_MEMBER_TASK"),
                    ("CREATION_SCHEDULE", "CREATION_SCHEDULE"),
                    ("EDIT_SCHEDULE", "EDIT_SCHEDULE"),
                    ("REMOVE_SCHEDULE", "REMOVE_SCHEDULE"),
                    ("REMOVE_TASK", "REMOVE_TASK"),
                    ("ASSIGNED_MEMBER_TO_TASK", "ASSIGNED_MEMBER_TO_TASK"),
                    ("UNASSIGNED_MEMBER_TO_TASK", "UNASSIGNED_MEMBER_TO_TASK"),
                ],
                default="MESSAGE",
                max_length=100,
            ),
        ),
    ]
