# Generated by Django 5.0.6 on 2024-11-29 11:44

from django.db import migrations
from django.core.management import call_command
from users.constants import RoleTypes


def transfer_data_roles(apps, schema_editor):
    """
    Transfer data roles
    """
    Role = apps.get_model("users", "Role")
    User = apps.get_model("users", "User")
    UserRole = apps.get_model("users", "UserRole")

    # Update system role
    Role.objects.exclude(name=RoleTypes.OPERATION_ADMIN.value).update(
        system_role=True
    )

    # Update user role
    for user in User.objects.all():
        UserRole.objects.create(company=user.company, role=user.role, user=user)

    # Seed data in role permissions
    call_command("seed_data_permissions")


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_permission_role_company_role_system_role_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(transfer_data_roles, migrations.RunPython.noop),
    ]
