# Generated by Django 5.0.6 on 2024-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
