# Generated by Django 5.0.6 on 2024-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_memo_is_open"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_enter_send_message",
        ),
        migrations.AddField(
            model_name="setting",
            name="is_enter_send_message",
            field=models.BooleanField(default=False),
        ),
    ]
