# Generated by Django 5.0.6 on 2025-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_is_enter_send_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="is_sorting_task_by_deadline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="setting",
            name="is_sorting_task_by_important",
            field=models.BooleanField(default=False),
        ),
    ]
