# Generated by Django 5.0.6 on 2025-02-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_setting_is_sorting_task_by_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
