# Generated by Django 5.0.6 on 2025-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0009_remove_dailyreport_is_confirmed_confirmreport_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="kanban_zoom",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="setting",
            name="schedule_zoom",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="setting",
            name="tab_visibility",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
