# Generated by Django 5.0.6 on 2025-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_setting_kanban_zoom_setting_schedule_zoom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="task_settings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
