# Generated by Django 5.0.6 on 2025-04-03 16:01

from django.db import migrations, models

from users.constants import AvatarColors


def seed_color(apps, schema_editor):
    """Seed the color of the organizations statistic categories"""
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        user.avatar_color = AvatarColors.random()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_setting_task_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(seed_color, migrations.RunPython.noop),
    ]
