# Generated by Django 5.0.6 on 2025-04-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_avatar_color"),
    ]

    operations = []
