# Generated by Django 5.0.6 on 2025-04-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_update_general_role_to_other_roles"),
    ]

    operations = []
