# Generated by Django 5.0.6 on 2025-04-14 19:01

from django.db import migrations
from roles.constants import ROLE_PERMISSIONS


def update_permission_to_role_default(apps, schema_editor):
    """
    Update permission to role default
    """
    Permission = apps.get_model("users", "Permission")
    RoleDetail = apps.get_model("users", "RoleDetail")
    Role = apps.get_model("users", "Role")

    for role_name, permissions in ROLE_PERMISSIONS.items():
        # Retrieve or create the role based on the role name
        role, created = Role.objects.get_or_create(name=role_name)
        for screen_name, actions in permissions.items():
            for action_name, selection_result in actions.items():
                screen_action = f"{screen_name}_{action_name}"
                permission_obj, created = Permission.objects.get_or_create(
                    name=screen_action
                )
                # Create a RoleDetail entry for the role, screen, and action
                RoleDetail.objects.update_or_create(
                    role=role,
                    permission=permission_obj,
                    defaults={"selection_result": selection_result},
                )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_update_general_role_to_other_roles"),
    ]

    operations = [
        migrations.RunPython(
            update_permission_to_role_default,
            reverse_code=migrations.RunPython.noop,
        )
    ]
