# Generated by Django 5.0.6 on 2025-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_update_permission_to_role_default"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="task_settings",
            new_name="task_filter",
        ),
        migrations.AddField(
            model_name="setting",
            name="date_filter_schedule_from",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="is_show_list_kanban",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="setting",
            name="is_show_my_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="setting",
            name="is_show_week_schedule",
            field=models.BooleanField(default=False),
        ),
    ]
