# Generated by Django 5.0.6 on 2025-06-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_avatar"),
    ]

    operations = []
