# Generated by Django 5.0.6 on 2025-06-16 15:52

from django.db import migrations


from roles.constants import GENERAL_PERMISSIONS, ROLE_PERMISSIONS
from users.constants import RoleTypes


def seed_data_role_permission_calendar_management(apps, schema_editor):
    """Seed data role permissions"""
    Permission = apps.get_model("users", "Permission")
    RoleDetail = apps.get_model("users", "RoleDetail")
    Role = apps.get_model("users", "Role")

    # Seed new permission to role default
    for role_name, permissions in ROLE_PERMISSIONS.items():
        # Retrieve or create the role based on the role name
        role, created = Role.objects.get_or_create(name=role_name)
        for screen_name, actions in permissions.items():
            for action_name, selection_result in actions.items():
                screen_action = f"{screen_name}_{action_name}"
                permission_obj, created = Permission.objects.get_or_create(
                    name=screen_action
                )
                # Create a RoleDetail entry for the role, screen, and action
                RoleDetail.objects.update_or_create(
                    role=role,
                    permission=permission_obj,
                    defaults={"selection_result": selection_result},
                )

    # Update other role by general role
    roles = Role.objects.exclude(name__in=[role.value for role in RoleTypes])
    for role in roles:
        for screen_name, actions in GENERAL_PERMISSIONS.items():
            for action_name, selection_result in actions.items():
                permission_obj, created = Permission.objects.get_or_create(
                    name=f"{screen_name}_{action_name}"
                )
                # Create a RoleDetail entry for the role, screen, and action
                RoleDetail.objects.update_or_create(
                    company=role.company,
                    role=role,
                    permission=permission_obj,
                    defaults={"selection_result": selection_result},
                )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_avatar"),
    ]

    operations = [
        migrations.RunPython(
            seed_data_role_permission_calendar_management,
            reverse_code=migrations.RunPython.noop,
        )
    ]
