# Generated by Django 5.0.6 on 2025-06-23 11:31

from django.db import migrations


from roles.constants import GENERAL_PERMISSIONS, ROLE_PERMISSIONS, Screens
from users.constants import RoleTypes


def update_data_permissions_to_roles_default(apps, schema_editor):
    """Seed data role permissions"""
    Permission = apps.get_model("users", "Permission")
    RoleDetail = apps.get_model("users", "RoleDetail")
    Role = apps.get_model("users", "Role")

    # Update new permission to role default
    for role_name, permissions in ROLE_PERMISSIONS.items():
        # Retrieve or create the role based on the role name
        role, created = Role.objects.get_or_create(name=role_name)
        for screen_name, actions in permissions.items():
            for action_name, selection_result in actions.items():
                screen_action = f"{screen_name}_{action_name}"
                permission_obj, created = Permission.objects.get_or_create(
                    name=screen_action
                )
                # Create a RoleDetail entry for the role, screen, and action
                RoleDetail.objects.update_or_create(
                    role=role,
                    permission=permission_obj,
                    defaults={"selection_result": selection_result},
                )

    # Assign calendar management permissions to other roles according to the general role
    roles = Role.objects.exclude(name__in=[role.value for role in RoleTypes])
    for role in roles:
        for screen_name, actions in GENERAL_PERMISSIONS.items():
            if screen_name == Screens.CALENDAR_MANAGEMENT.value:
                for action_name, selection_result in actions.items():
                    permission_obj, created = Permission.objects.get_or_create(
                        name=f"{screen_name}_{action_name}"
                    )
                    # Create a RoleDetail entry for the role, screen, and action
                    RoleDetail.objects.update_or_create(
                        company=role.company,
                        role=role,
                        permission=permission_obj,
                        defaults={"selection_result": selection_result},
                    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_update_permission_calendar_management"),
    ]

    operations = [
        migrations.RunPython(
            update_data_permissions_to_roles_default,
            reverse_code=migrations.RunPython.noop,
        )
    ]
