# Generated by Django 5.0.6 on 2025-07-11 18:45

from django.db import migrations


def update_organization_referenced_by_task_for_users(apps, schema_editor):
    """
    Ensure users are linked to organizations referenced by their in-charge tasks, and assign missing organizations to tasks.
    """
    User = apps.get_model("users", "User")
    Organization = apps.get_model("organizations", "Organization")

    for user in User.objects.all():
        # Get user's organization IDs and those referenced by their in-charge tasks
        my_orgs = set(user.organizations.values_list("id", flat=True))
        orgs_with_tasks = set(
            user.in_charge_tasks.exclude(organization__isnull=True).values_list(
                "organization", flat=True
            )
        )
        orgs_to_add = orgs_with_tasks - my_orgs

        # Add missing organizations to user
        if orgs_to_add:
            orgs = Organization.objects.filter(id__in=orgs_to_add)
            for org in orgs:
                user.organizations.add(
                    org,
                    through_defaults={
                        "company": user.company,
                        "is_main": False,
                    },
                )
                print(f"[AddOrgToUser] user_id={user.id}, add_org_id={org.id}")

        # Assign user's first organization to their in-charge tasks missing organization
        first_org = user.organizations.first()
        if first_org:
            tasks_without_org = user.in_charge_tasks.filter(
                organization__isnull=True
            )
            for task in tasks_without_org:
                task.organization = first_org
                task.save(update_fields=["organization"])
                print(
                    f"[AssignOrgToTask] task_id={task.id}, assign_org_id={first_org.id}"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_seed_default_organization_calendar"),
        ("tasks", "0020_taskduration_tasks_taskd_started_796d43_idx_and_more"),
        ("users", "0019_update_permissions_to_roles_default"),
    ]

    operations = [
        migrations.RunPython(
            update_organization_referenced_by_task_for_users,
            reverse_code=migrations.RunPython.noop,
        )
    ]
