# Generated by Django 5.0.6 on 2025-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_loginbonus_taskrewardlog_transactionhistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("タスク完了", "TASK_COMPLETE"),
                    ("ログインボーナス", "LOGIN_BONUS"),
                    ("チュートリアル", "TUTORIAL"),
                    ("作業時間計測", "WORK_TIME"),
                    ("サンクスポイント", "THANKS_MSG"),
                    ("MVP投票", "VOTE_MVP"),
                    ("スキルアップ", "SKILL_UP"),
                    ("ポイント交換", "EXCHANGE"),
                    ("アイテム交換", "BUY_ITEM"),
                    ("その他", "OTHER"),
                ],
                default="その他",
                max_length=50,
            ),
        ),
    ]
