# Generated by Django 5.0.6 on 2025-09-16 10:34

from django.db import migrations

PLANS = {
    "plan_1_10": {
        "name": "Plan 1-10",
        "monthly_fee": 29000,  # Monthly fee (JPY)
        "exchangeable_amount": 3000,  # Amount convertible to DotMoney
        "max_exchange_per_user": 3000,  # Max convertible per user per month
        "min_exchange_per_user": 300,  # Min convertible per user per month
    },
    "plan_11_20": {
        "name": "Plan 11-20",
        "monthly_fee": 58000,
        "exchangeable_amount": 6000,
        "max_exchange_per_user": 545,
        "min_exchange_per_user": 300,
    },
    "plan_21_30": {
        "name": "Plan 21-30",
        "monthly_fee": 78000,
        "exchangeable_amount": 10000,
        "max_exchange_per_user": 476,
        "min_exchange_per_user": 333,
    },
}


def update_exchangeable_amount_user(apps, schema_editor):
    """Update exchangeable amount for users based on company plan"""
    Company = apps.get_model("companies", "Company")
    UserBalance = apps.get_model("users", "UserBalance")
    companies = Company.objects.all()
    for company in companies:
        user_count = company.users.count()
        if user_count <= 10:
            plan = PLANS["plan_1_10"]
        elif user_count <= 20:
            plan = PLANS["plan_11_20"]
        else:
            plan = PLANS["plan_21_30"]

        exchangeable_amount = plan["exchangeable_amount"]
        exchange_per_user = exchangeable_amount // user_count

        for user in company.users.all():
            UserBalance.objects.update_or_create(
                user=user,
                company=user.company,
                defaults={
                    "exchangeable_coin": min(exchange_per_user, 300),
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_transactionhistory_transaction_type"),
    ]

    operations = [
        migrations.RunPython(
            update_exchangeable_amount_user,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
