# Generated by Django 5.0.6 on 2025-10-06 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reverse_remove_user_id_is_null(apps, schema_editor):
    """Remove user is null"""
    TransactionHistory = apps.get_model("users", "TransactionHistory")
    TransactionHistory.objects.filter(user_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_useractivitylog"),
        ("companies", "0007_company_target_user_count_company_total_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="company_balance_after",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("タスク完了", "TASK_COMPLETE"),
                    ("ログインボーナス", "LOGIN_BONUS"),
                    ("チュートリアル", "TUTORIAL"),
                    ("作業時間計測", "WORK_TIME"),
                    ("サンクスポイント", "THANKS_MSG"),
                    ("MVP投票", "VOTE_MVP"),
                    ("スキルアップ", "SKILL_UP"),
                    ("ポイント交換", "EXCHANGE"),
                    ("アイテム交換", "BUY_ITEM"),
                    ("その他", "OTHER"),
                    ("プラン自動付与", "PLAN_AUTO"),
                    ("プラン自動付与コイン失効", "PLAN_AUTO_EXPIRE"),
                ],
                default="その他",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop, reverse_remove_user_id_is_null
        ),
    ]
