# Generated by Django 5.0.6 on 2025-10-15 11:40

from datetime import datetime, timedelta
from django.db import migrations


def clear_login_token(apps, schema_editor):
    """Delete all login tokens older than 16 hours"""
    LoginToken = apps.get_model("users", "LoginToken")
    cutoff_time = datetime.now() - timedelta(hours=16)
    LoginToken.objects.filter(updated_at__lt=cutoff_time).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_update_permission_point_payment_survey"),
    ]

    operations = [
        migrations.RunPython(
            clear_login_token,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
