# Generated by Django 5.0.6 on 2025-10-24 17:03

from django.db import migrations


from roles.constants import ROLE_PERMISSIONS


def update_data_permissions(apps, schema_editor):
    """Seed data role permissions"""
    Permission = apps.get_model("users", "Permission")
    RoleDetail = apps.get_model("users", "RoleDetail")
    LoginToken = apps.get_model("users", "LoginToken")
    Role = apps.get_model("users", "Role")

    # Update new permission to role default
    for role_name, permissions in ROLE_PERMISSIONS.items():
        # Retrieve or create the role based on the role name
        role, created = Role.objects.get_or_create(name=role_name)
        for screen_name, actions in permissions.items():
            for action_name, selection_result in actions.items():
                screen_action = f"{screen_name}_{action_name}"
                permission_obj, created = Permission.objects.get_or_create(
                    name=screen_action
                )
                # Create a RoleDetail entry for the role, screen, and action
                RoleDetail.objects.update_or_create(
                    role=role,
                    permission=permission_obj,
                    defaults={"selection_result": selection_result},
                )

    # Block all access tokens, force all users to log in again to update permissions
    LoginToken.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_clear_token_login"),
    ]

    operations = [
        migrations.RunPython(
            update_data_permissions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
