# Generated by Django 5.1.15 on 2026-03-11 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from users.utils import calculate_coin_expires_at


def backfill_coin_lots(apps, schema_editor):
    UserBalance = apps.get_model("users", "UserBalance")
    UserCoinLot = apps.get_model("users", "UserCoinLot")

    now_at = django.utils.timezone.now()
    expires_at = calculate_coin_expires_at(now_at)

    rows = []
    for bal in UserBalance.objects.filter(coin__gt=0).iterator():
        rows.append(
            UserCoinLot(
                user_id=bal.user_id,
                company_id=bal.company_id,
                amount_remaining=bal.coin,
                granted_at=now_at,
                expires_at=expires_at,
            )
        )

    if rows:
        UserCoinLot.objects.bulk_create(rows, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_companyplan_exchangeable_amount_and_more"),
        ("users", "0030_update_actual_duration_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("タスク完了", "TASK_COMPLETE"),
                    ("ログインボーナス", "LOGIN_BONUS"),
                    ("チュートリアル", "TUTORIAL"),
                    ("作業時間計測", "WORK_TIME"),
                    ("サンクスポイント", "THANKS_MSG"),
                    ("MVP投票", "VOTE_MVP"),
                    ("スキルアップ", "SKILL_UP"),
                    ("ポイント交換", "EXCHANGE"),
                    ("アイテム交換", "BUY_ITEM"),
                    ("その他", "OTHER"),
                    ("プラン自動付与", "PLAN_AUTO"),
                    ("プラン自動付与コイン失効", "PLAN_AUTO_EXPIRE"),
                    ("失効", "COIN_EXPIRE"),
                ],
                default="その他",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserCoinLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount_remaining", models.IntegerField(default=0)),
                (
                    "granted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coin_lots",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            backfill_coin_lots, reverse_code=migrations.RunPython.noop
        ),
    ]
