# Generated by Django 5.0.6 on 2025-09-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.CharField(),
        ),
    ]
