# Generated by Django 5.0.6 on 2024-11-14 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmap",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_maps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="skillmaphistory",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_map_histories",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="skillmaphistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_map_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statisticcategory",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistic_categories",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="skillmaphistory",
            name="statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_map_histories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="skillmaphistory",
            name="superior_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superior_statistic_category_map_histories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="skillmap",
            name="large_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_large_skill_maps",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="skillmap",
            name="medium_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_medium_skill_maps",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="skillmap",
            name="small_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_small_skill_maps",
                to="skills.statisticcategory",
            ),
        ),
    ]
