# Generated by Django 5.0.6 on 2024-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="statisticcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
