# Generated by Django 5.0.6 on 2024-11-28 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_rename_level_organizationsskills_levels"),
        ("skills", "0003_alter_skill_name_alter_statisticcategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillmap",
            name="large_statistic_category",
        ),
        migrations.RemoveField(
            model_name="skillmap",
            name="medium_statistic_category",
        ),
        migrations.RemoveField(
            model_name="skillmap",
            name="small_statistic_category",
        ),
        migrations.AddField(
            model_name="skillmap",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skill_maps",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="skillmap",
            name="level",
            field=models.CharField(
                choices=[
                    ("レベル0", "LEVEL_0"),
                    ("レベル1", "LEVEL_1"),
                    ("レベル2", "LEVEL_2"),
                    ("レベル3", "LEVEL_3"),
                ],
                default="レベル0",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skillmap",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_maps",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="skillmaphistory",
            name="level",
            field=models.CharField(
                choices=[
                    ("レベル0", "LEVEL_0"),
                    ("レベル1", "LEVEL_1"),
                    ("レベル2", "LEVEL_2"),
                    ("レベル3", "LEVEL_3"),
                ],
                default="レベル0",
                max_length=20,
            ),
        ),
    ]
