# Generated by Django 5.0.6 on 2025-01-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_remove_skillmap_large_statistic_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillmap",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_maps",
                to="skills.skill",
            ),
        ),
    ]
