# Generated by Django 5.0.6 on 2025-02-11 19:00

from django.db import migrations, models
import random


def generate_random_color():
    """Generate a random hex color code."""
    return "#{:06x}".format(random.randint(0, 0xFFFFFF))


def seed_color(apps, schema_editor):
    """
    Seed colors for large statistic categories grouped by organization.
    """
    categories = apps.get_model("skills", "StatisticCategory")
    for category in categories.objects.all():
        category.color = generate_random_color()
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0005_alter_skillmap_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticcategory",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(seed_color, migrations.RunPython.noop),
    ]
