# Generated by Django 5.0.6 on 2025-02-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0006_statisticcategory_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statisticcategory",
            name="color",
        ),
    ]
