# Generated by Django 5.0.6 on 2025-04-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_organization_hierarchize_at"),
        ("skills", "0007_remove_statisticcategory_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticcategory",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_statistic_categories",
                to="organizations.organization",
            ),
        ),
    ]
