# Generated by Django 5.0.6 on 2025-05-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("organizations", "0015_remove_organization_skills_step_and_more"),
        ("skills", "0008_statisticcategory_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillmap",
            name="index",
        ),
        migrations.RemoveField(
            model_name="skillmap",
            name="level",
        ),
        migrations.RemoveField(
            model_name="skillmap",
            name="point",
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_skill",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="step",
            field=models.CharField(
                choices=[
                    ("ステップ1", "STEP_1"),
                    ("ステップ2", "STEP_2"),
                    ("ステップ3", "STEP_3"),
                ],
                default="ステップ1",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skillmap",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skillmap",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skillmap",
            name="skill_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_maps_skill_parent",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="skillmap",
            name="step",
            field=models.CharField(
                choices=[
                    ("ステップ1", "STEP_1"),
                    ("ステップ2", "STEP_2"),
                    ("ステップ3", "STEP_3"),
                ],
                default="ステップ1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skillmap",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_maps",
                to="skills.skill",
            ),
        ),
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("レベル1", "LEVEL_1"),
                            ("レベル2", "LEVEL_2"),
                            ("レベル3", "LEVEL_3"),
                        ],
                        default="レベル1",
                        max_length=20,
                    ),
                ),
                ("items", models.JSONField(blank=True, null=True)),
                (
                    "measure_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "measure_time",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "look_back_interval",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "look_back_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAY", "DAY"),
                            ("WEEK", "WEEK"),
                            ("MONTH", "MONTH"),
                            ("YEAR", "YEAR"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_levels",
                        to="companies.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_levels",
                        to="organizations.organization",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_levels",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillMapSkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("レベル1", "LEVEL_1"),
                            ("レベル2", "LEVEL_2"),
                            ("レベル3", "LEVEL_3"),
                        ],
                        default="レベル1",
                        max_length=20,
                    ),
                ),
                (
                    "measure_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "actual_measure_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "measure_time",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "actual_measure_time",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("items", models.JSONField(blank=True, null=True)),
                (
                    "look_back_interval",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "look_back_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAY", "DAY"),
                            ("WEEK", "WEEK"),
                            ("MONTH", "MONTH"),
                            ("YEAR", "YEAR"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "start_lookback_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("next_submit_at", models.DateTimeField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_map_skill_levels",
                        to="companies.company",
                    ),
                ),
                (
                    "skill_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_map_skill_levels",
                        to="skills.skilllevel",
                    ),
                ),
                (
                    "skill_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_map_skill_levels",
                        to="skills.skillmap",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="SkillMapHistory",
        ),
    ]
