# Generated by Django 5.0.6 on 2025-04-25 11:29

from django.db import migrations


def clear_data_skill(apps, schema_editor):
    """
    Handle clear data skill not have organization
    """
    Skill = apps.get_model("skills", "Skill")
    SkillMap = apps.get_model("skills", "SkillMap")
    Skill.objects.filter(organization__isnull=True).delete()
    SkillMap.objects.filter(skill__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0009_remove_skillmap_index_remove_skillmap_level_and_more"),
    ]

    operations = [
        migrations.RunPython(clear_data_skill, migrations.RunPython.noop),
    ]
