# Generated by Django 5.0.6 on 2025-05-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0010_clear_data_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmapskilllevel",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_map_skill_levels",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="skillmapskilllevel",
            name="actual_measure_time",
            field=models.CharField(
                blank=True, default="00:00:00", max_length=255, null=True
            ),
        ),
    ]
