# Generated by Django 5.0.6 on 2025-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0012_update_actual_measure_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmapskilllevel",
            name="popup",
            field=models.BooleanField(default=True),
        ),
    ]
