# Generated by Django 5.0.6 on 2025-05-23 20:01

from django.db import migrations


def clear_data_skill(apps, schema_editor):
    """
    Handle clear data skill not have organization
    """
    Skill = apps.get_model("skills", "Skill")
    Skill.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0013_skillmapskilllevel_popup"),
    ]

    operations = [
        migrations.RunPython(clear_data_skill, migrations.RunPython.noop),
    ]
