# Generated by Django 5.0.6 on 2025-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0014_clear_data_all_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmapskilllevel",
            name="measure_task_ids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
