# Generated by Django 5.0.6 on 2025-08-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0015_skillmapskilllevel_measure_task_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmap",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
