# Generated by Django 5.0.6 on 2025-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0016_skillmap_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillmap",
            name="is_default",
        ),
        migrations.AddField(
            model_name="skillmap",
            name="set_default_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
