# Generated by Django 5.0.6 on 2025-11-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0017_remove_skillmap_is_default_skillmap_set_default_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmapskilllevel",
            name="measure_task_duration_ids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
