steps:
  # Build Docker Image on Cloud Build
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['_ADMIN_ARTIFACT_REGISTRY_PATH', '_BUILD_ENV']
    args:
      - "-c"
      - |
        # Extract value from .env format
        extract_env() {
          echo "$$_BUILD_ENV" | grep "^$1=" | cut -d '=' -f2-
        }

        docker build --platform linux/amd64 \
          --build-arg NEXT_PUBLIC_API_URL="$$(extract_env NEXT_PUBLIC_API_URL)" \
          --build-arg API_INTERNAL_URL="$$(extract_env API_INTERNAL_URL)" \
          --build-arg RUNTIME_ENV_PATH=$_RUNTIME_ENV_PATH \
          -t $$_ADMIN_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
          -f Dockerfile.staging .

  # Push built Docker Image on Artifact Registry
  - id: 'Push Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: ['_ADMIN_ARTIFACT_REGISTRY_PATH']
    args: ['-c', 'docker push $$_ADMIN_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA']

  # Run built Docker Image on Cloud Run
  - id: 'Run Docker Image'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    secretEnv:
      ['_ADMIN_ARTIFACT_REGISTRY_PATH', '_ADMIN_REGION', '_ADMIN_SERVICE_NAME']
    args: [
        '-c',
        "gcloud run deploy $$_ADMIN_SERVICE_NAME \
        --image $$_ADMIN_ARTIFACT_REGISTRY_PATH:$COMMIT_SHA \
        --region $$_ADMIN_REGION \
        --port 3000 \
        --allow-unauthenticated \
        --update-secrets=$_RUNTIME_ENV_PATH=$_SECRET_ENV_NAME:latest",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Secret Manager settings
  _SECRET_ENV_NAME: STG_ADMIN_ENV
  _RUNTIME_ENV_PATH: /secrets/.env

# Settings SecretManager
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_ADMIN_ARTIFACT_REGISTRY_PATH/versions/latest
      env: _ADMIN_ARTIFACT_REGISTRY_PATH
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_ADMIN_REGION/versions/latest
      env: _ADMIN_REGION
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_ADMIN_SERVICE_NAME/versions/latest
      env: _ADMIN_SERVICE_NAME
    - versionName: projects/${PROJECT_NUMBER}/secrets/STG_ADMIN_ENV/versions/latest
      env: _BUILD_ENV
