version: '3.8'

networks:
  office_dock_network:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: officedock-admin
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    networks:
      - office_dock_network
