# Use the official Node.js 16.x image as a base
FROM node:21-alpine3.17

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

RUN npm run build

EXPOSE 3000

ENV PORT 3000

# Start the application
CMD ["npm", "run", "start"]