# Generated by Django 5.0.6 on 2025-09-19 11:45
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField()),
                ("monthly_fee", models.FloatField()),
                ("stripe_product_id", models.CharField(blank=True, null=True)),
                ("stripe_price_id", models.CharField(blank=True, null=True)),
                ("exchangeable_amount", models.IntegerField(default=0)),
                ("limit_person", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField()),
                ("percentage", models.FloatField()),
                ("stripe_tax_id", models.CharField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
