# Generated by Django 5.0.6 on 2025-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_custom_plan",
            field=models.BooleanField(default=False),
        ),
    ]
