# Generated by Django 5.0.6 on 2025-11-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_plan_is_custom_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="monthly_fee",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
