# Generated by Django 5.0.6 on 2025-11-18 19:40

from django.db import migrations, models
from plans.constants import CONSUMPTION_TAX, PLANS, TAX_PERCENTAGE
from common.services.stripe_service import StripeService


def seed_plan_default(apps, schema_editor):
    """
    Seed default company plan by total user
    """
    Plan = apps.get_model("plans", "Plan")

    stripe = StripeService()
    stripe.get_or_create_tax_rate(TAX_PERCENTAGE, CONSUMPTION_TAX)

    for plan in PLANS:
        stripe_product, stripe_price = stripe.create_product_with_price(
            name=plan["name"],
            amount=plan["monthly_fee"],
            currency="jpy",
            interval="month",
        )
        Plan.objects.update_or_create(
            name=plan["name"],
            defaults={
                "monthly_fee": plan["monthly_fee"],
                "stripe_product_id": stripe_product.id,
                "stripe_price_id": stripe_price.id,
                "exchangeable_amount": plan["exchangeable_amount"],
                "limit_person": plan["limit_person"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_plan_is_custom_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="monthly_fee",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(seed_plan_default, migrations.RunPython.noop),
    ]
