# Generated by Django 5.0.6 on 2025-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_show_holidays_calendar",
            field=models.BooleanField(default=False),
        ),
    ]
