# Generated by Django 5.0.6 on 2025-09-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_is_show_holidays_calendar"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="status",
        ),
        migrations.AddField(
            model_name="company",
            name="max_user_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="max_user_in_contract_period",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("申請中", "PENDING_APPROVAL"),
                    ("契約中", "ACTIVE_CONTRACT"),
                    ("決済失敗", "RETRY_PAYMENT"),
                    ("利用停止中", "SUSPENDED"),
                    ("解約予約中", "CANCELLATION_PENDING"),
                    ("解約済", "CONTRACT_TERMINATED"),
                    ("仮利用", "TEMPORARY_USAGE"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_customer_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="address",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="cancel_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="implementation_main_issue",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="industry",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="next_renewal_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="phone",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="responsible_person_mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="responsible_person_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="system_main_purpose",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CompanyPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(blank=True, null=True)),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, null=True),
                ),
                ("stripe_fingerprint", models.CharField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "stripe_subscription_item_id",
                    models.CharField(blank=True, null=True),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="companies.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_plans",
                        to="plans.plan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "INVOICE"),
                            ("PLAN", "PLAN"),
                            ("POINT", "POINT"),
                        ]
                    ),
                ),
                ("invoice_target", models.DateField(blank=True, null=True)),
                ("plan_start_at", models.DateTimeField(blank=True, null=True)),
                ("plan_end_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("stripe_invoice_id", models.CharField(blank=True, null=True)),
                ("amount_point", models.IntegerField(blank=True, null=True)),
                ("retry_attempt", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="companies.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plans.plan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
