# Generated by Django 5.0.6 on 2025-09-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0003_remove_contract_status_company_max_user_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyplan",
            name="stripe_subscription_item_id",
        ),
    ]
