# Generated by Django 5.0.6 on 2025-09-26 17:03

import django.db.models.deletion
from django.db import migrations, models


def clean_data_of_fields_change_to_json(apps, schema_editor):
    """Clean data of fields change to json"""
    Contract = apps.get_model("companies", "Contract")
    for contract in Contract.objects.all():
        contract.system_main_purpose = []
        contract.implementation_main_issue = []
        contract.save(
            update_fields=["system_main_purpose", "implementation_main_issue"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_companyplan_stripe_subscription_item_id"),
    ]

    operations = [
        migrations.RunPython(
            clean_data_of_fields_change_to_json, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="contract",
            name="implementation_main_issue",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="responsible_person_mail",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="responsible_person_name",
        ),
        migrations.AddField(
            model_name="company",
            name="responsible_person_mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="responsible_person_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="department",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyplan",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_plan",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="system_main_purpose",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
