# Generated by Django 5.0.6 on 2025-10-03 12:32

from django.db import migrations, models

import stripe

from companies.constants import PaymentTypes
from core import settings


def update_info_card(apps, schema_editor):
    """
    Handle get info from Stripe and store to DB
    """
    CompanyPaymentMethod = apps.get_model("companies", "CompanyPaymentMethod")
    stripe.api_key = settings.STRIPE_SECRET_KEY

    for company_payment_method in CompanyPaymentMethod.objects.all():
        try:
            payment_method = stripe.PaymentMethod.retrieve(
                company_payment_method.stripe_payment_method_id
            )
            data = {
                "last4": payment_method.card.last4,
                "exp_month": payment_method.card.exp_month,
                "exp_year": payment_method.card.exp_year,
                "brand": payment_method.card.brand,
                "stripe_fingerprint": payment_method.card.fingerprint,
                "type": PaymentTypes.CREDIT_CARD.value,
            }
            company_payment_method.__dict__.update(data)
            company_payment_method.save(update_fields=data.keys())
        except Exception as e:
            print("Error ", e)
            company_payment_method.delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0005_remove_contract_implementation_main_issue_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companypaymentmethod",
            name="brand",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companypaymentmethod",
            name="exp_month",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companypaymentmethod",
            name="exp_year",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companypaymentmethod",
            name="is_retry_failed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companypaymentmethod",
            name="last4",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RunPython(update_info_card, migrations.RunPython.noop),
    ]
