# Generated by Django 5.0.6 on 2025-10-06 00:20

from django.db import migrations, models


def update_exchangeable(apps, schema_editor):
    """Update exchangeable amount for company"""
    Company = apps.get_model("companies", "Company")
    companies = Company.objects.all()
    for company in companies:
        exchangeable_amount = (
            company.company_plan.plan.exchangeable_amount
            if hasattr(company, "company_plan")
            and hasattr(company.company_plan, "plan")
            else 0
        )
        total_coins = exchangeable_amount
        target_user_count = company.users.count()
        coins_remaining = 0
        for user in company.users.all():
            coins_remaining += (
                user.balances.coin if hasattr(user, "balances") else 0
            )
        company.total_coins = total_coins
        company.coins_remaining = coins_remaining
        company.target_user_count = target_user_count
        company.save(
            update_fields=[
                "total_coins",
                "target_user_count",
                "coins_remaining",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_companypaymentmethod_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="target_user_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="total_coins",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="coins_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(update_exchangeable, migrations.RunPython.noop),
    ]
