# Generated by Django 5.0.6 on 2025-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_company_target_user_count_company_total_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="close_date",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="company",
            name="editable_after_closing",
            field=models.IntegerField(default=10),
        ),
    ]
