# Generated by Django 5.0.6 on 2025-10-10 20:46

from django.db import migrations


def update_close_date(apps, schema_editor):
    """Update close date"""
    Company = apps.get_model("companies", "Company")
    for c in Company.objects.all():
        c.close_date = 31
        c.save(update_fields=["close_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_company_close_date_company_editable_after_closing"),
    ]

    operations = [
        migrations.RunPython(update_close_date, migrations.RunPython.noop),
    ]
