# Generated by Django 5.0.6 on 2025-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_update_close_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="close_date",
            field=models.IntegerField(default=31),
        ),
    ]
