# Generated by Django 5.0.6 on 2025-11-17 13:00

from django.db import migrations, models


def seed_default_payment_type(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    for c in Company.objects.all():
        if pm := c.payment_methods.first():
            c.payment_type = pm.type
            c.save(update_fields=["payment_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_alter_company_close_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="mf_customer_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RunPython(
            seed_default_payment_type, migrations.RunPython.noop
        ),
    ]
