# Generated by Django 5.0.6 on 2025-11-18 19:37

from django.db import migrations, models
import stripe

from core import settings
from plans.constants import CUSTOM_PLAN


def get_data_plan_to_company_plan(apps, schema_editor):
    """Handle get data plan to company plan"""
    stripe.api_key = settings.STRIPE_SECRET_KEY
    Plan = apps.get_model("plans", "Plan")
    apps.get_model("companies", "CompanyPlan")
    main_cp, created = Plan.objects.get_or_create(
        name=CUSTOM_PLAN, monthly_fee__isnull=True, is_custom_plan=True
    )
    if created:
        product = stripe.Product.create(name=CUSTOM_PLAN)
        main_cp.stripe_product_id = product.id
        main_cp.save(update_fields=["stripe_product_id"])
        product_id = product.id
    else:
        product_id = main_cp.stripe_product_id
    plans = Plan.objects.filter(monthly_fee__isnull=False).all()
    for plan in plans:
        stripe_price_id = plan.stripe_price_id
        price = None
        if plan.is_custom_plan:
            price_data = {
                "unit_amount": int(plan.monthly_fee),
                "currency": "jpy",
                "product": product_id,
                "recurring": {
                    "interval": "month",
                },
                "billing_scheme": "per_unit",
            }
            prices = stripe.Price.list(product=product_id)
            price = None
            for p in prices.data:
                if p.unit_amount == price_data["unit_amount"]:
                    price = p
                    break
            if not price:
                # Add price to main custom plan
                price = stripe.Price.create(**price_data)
            stripe_price_id = price.id
        comp_plans = plan.company_plans.all()
        # Update new price to subscription
        for c_plan in comp_plans:
            c_plan.monthly_fee = plan.monthly_fee
            c_plan.stripe_price_id = stripe_price_id
            c_plan.exchangeable_amount = plan.exchangeable_amount
            c_plan.limit_person = plan.limit_person
            c_plan.plan = main_cp if plan.is_custom_plan else plan
            c_plan.save(
                update_fields=[
                    "monthly_fee",
                    "stripe_price_id",
                    "exchangeable_amount",
                    "limit_person",
                    "plan",
                ]
            )
            if not plan.is_custom_plan and not price:
                continue
            try:
                if not c_plan.stripe_subscription_id:
                    continue
                stripe_sub = stripe.Subscription.retrieve(
                    c_plan.stripe_subscription_id
                )
                subscription_item_id = stripe_sub["items"]["data"][0]["id"]
                # Create fixed subscription billing at the end of the month
                subscription = stripe.Subscription.modify(
                    stripe_sub.id,
                    items=[
                        {
                            "id": subscription_item_id,
                            "price": price,
                        }
                    ],
                    proration_behavior="none",  # No prorate for current month
                )
            except stripe.error.InvalidRequestError as e:
                continue
            except stripe.error.StripeError as e:
                continue
            except Exception:
                continue
        # Delete current custom plan
        if plan.is_custom_plan and plan.monthly_fee is not None:
            prices = stripe.Price.list(product=plan.stripe_product_id)
            for price in prices.data:
                stripe.Price.modify(price.id, active=False)
            try:
                stripe.Product.delete(plan.stripe_product_id)
            except:
                stripe.Product.modify(plan.stripe_product_id, active=False)
            plan.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plan_monthly_fee"),
        ("companies", "0011_company_mf_customer_id_company_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyplan",
            name="exchangeable_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="companyplan",
            name="limit_person",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="companyplan",
            name="monthly_fee",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyplan",
            name="stripe_price_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RunPython(
            get_data_plan_to_company_plan, migrations.RunPython.noop
        ),
    ]
