# Generated by Django 5.0.6 on 2025-08-29 17:49

import django.db.models.deletion
import mvp_votes.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp_votes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mvpvotemanagement",
            name="is_start",
        ),
        migrations.AddField(
            model_name="mvpvote",
            name="mvp_vote_management",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="mvp_votes.mvpvotemanagement",
            ),
        ),
        migrations.AddField(
            model_name="mvpvotemanagement",
            name="type",
            field=models.CharField(
                choices=mvp_votes.constants.MVPVoteTypes.choices,
                default="UPCOMING",
                max_length=30,
            ),
        ),
    ]
