# Generated by Django 5.0.6 on 2025-09-04 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mvp_votes", "0002_remove_mvpvotemanagement_is_start_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mvpvote",
            unique_together={("mvp_vote_management", "voter")},
        ),
    ]
