# Generated by Django 5.0.6 on 2025-09-04 19:37

from django.conf import settings
from django.db import migrations


def unique_mvp_vote_management(apps, schema_editor):
    """
    Seed task duration by user
    """
    mvp_votes = apps.get_model("mvp_votes", "MVPVote")
    # unique mvp vote management by voter
    seen = set()
    for vote in mvp_votes.objects.all():
        key = (vote.mvp_vote_management_id, vote.voter_id)
        if key in seen:
            vote.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("mvp_votes", "0002_remove_mvpvotemanagement_is_start_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            unique_mvp_vote_management, migrations.RunPython.noop
        ),
        migrations.AlterUniqueTogether(
            name="mvpvote",
            unique_together={("mvp_vote_management", "voter")},
        ),
    ]
