# Generated by Django 5.0.6 on 2024-11-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("organizations", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsskills",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizations_skills",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="skills",
            field=models.ManyToManyField(
                related_name="organizations",
                through="organizations.OrganizationsSkills",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="organizationsstatisticcategories",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations_statistic_categories",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="organizationsstatisticcategories",
            name="large_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizations_large_statistic_categories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="organizationsstatisticcategories",
            name="medium_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizations_medium_statistic_categories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="organizationsstatisticcategories",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations_statistic_categories",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationsstatisticcategories",
            name="small_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizations_small_statistic_categories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="statistic_categories",
            field=models.ManyToManyField(
                related_name="organizations",
                through="organizations.OrganizationsStatisticCategories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="usersorganizations",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_organizations",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="usersorganizations",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
