# Generated by Django 5.0.6 on 2024-11-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("organizations", "0003_initial"),
        ("skills", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationsStatisticCategoriesSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations_statistic_categories_skills",
                        to="companies.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations_statistic_categories_skills",
                        to="organizations.organization",
                    ),
                ),
                (
                    "organization_statistic_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations_statistic_categories_skills",
                        to="organizations.organizationsstatisticcategories",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations_statistic_categories_skills",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
