# Generated by Django 5.0.6 on 2024-11-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organizationsstatisticcategoriesskills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationsskills",
            old_name="level",
            new_name="levels",
        ),
    ]
