# Generated by Django 5.0.6 on 2024-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_rename_level_organizationsskills_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersorganizations",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
