# Generated by Django 5.0.6 on 2025-01-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_usersorganizations_is_main"),
        ("skills", "0005_alter_skillmap_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsskills",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations_skills",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsstatisticcategories",
            name="large_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations_large_statistic_categories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsstatisticcategories",
            name="medium_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations_medium_statistic_categories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AlterField(
            model_name="organizationsstatisticcategories",
            name="small_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations_small_statistic_categories",
                to="skills.statisticcategory",
            ),
        ),
    ]
