# Generated by Django 5.0.6 on 2025-02-25 15:35

from django.db import migrations, models

from organizations.constants import CategoryColors


def seed_color(apps, schema_editor):
    """Seed the color of the organizations statistic categories"""
    Organization = apps.get_model("organizations", "Organization")
    organization_category = apps.get_model(
        "organizations", "OrganizationsStatisticCategories"
    )
    for organization in Organization.objects.all():
        if organization.organizations_statistic_categories.exists():
            large_categories = (
                organization.organizations_statistic_categories.values(
                    "large_statistic_category"
                ).distinct()
            )
            for cat in list(large_categories):
                organization_category.objects.filter(
                    organization__id=organization.id,
                    large_statistic_category__id=cat[
                        "large_statistic_category"
                    ],
                ).update(color=CategoryColors.random())


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_organizationsskills_skill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsstatisticcategories",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(seed_color, migrations.RunPython.noop),
    ]
