# Generated by Django 5.0.6 on 2025-04-02 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_organizationsstatisticcategories_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/icons",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
