# Generated by Django 5.0.6 on 2025-04-03 19:22

import uuid
from django.db import migrations, models


def generate_unique_uuid(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    for task in Organization.objects.all():
        task.uuid = uuid.uuid4()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_organization_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(unique=True, null=True),
        ),
        migrations.RunPython(
            generate_unique_uuid, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False),
        ),
    ]
