# Generated by Django 5.0.6 on 2025-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_organization_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[("NORMAL", "NORMAL"), ("PROJECT", "PROJECT")],
                default="NORMAL",
                max_length=50,
            ),
        ),
    ]
