# Generated by Django 5.0.6 on 2025-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_organization_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="hierarchize_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
