# Generated by Django 5.0.6 on 2025-04-15 11:51

from django.db import migrations, transaction
from django.db.models import Q


def clear_task_category_not_in_category_hierarchy(apps, schema_editor):
    """
    Seed task duration by user
    """
    Organization = apps.get_model("organizations", "Organization")
    Task = apps.get_model("tasks", "Task")
    Schedule = apps.get_model("calendars", "Schedule")
    not_null_tasks = Task.objects.filter(
        categories__large_statistic_category__isnull=False
    ).all()
    not_null_schedules = Schedule.objects.filter(
        categories__large_statistic_category__isnull=False
    ).all()
    with transaction.atomic():
        for organization in Organization.objects.all():
            large_category_ids = organization.organizations_statistic_categories.distinct().values_list(
                "large_statistic_category", flat=True
            )
            if large_category_ids:
                tasks = not_null_tasks.filter(
                    ~Q(
                        categories__large_statistic_category__in=large_category_ids
                    )
                    & Q(organization=organization)
                )
                schedules = not_null_schedules.filter(
                    ~Q(
                        categories__large_statistic_category__in=large_category_ids
                    )
                    & Q(organization=organization)
                )
                if tasks.exists():
                    for task in tasks:
                        task.categories.clear()
                if schedules.exists():
                    for schedule in schedules:
                        schedule.categories.clear()
                for large_statistic_category in large_category_ids:
                    medium_category_ids = (
                        organization.organizations_statistic_categories.filter(
                            large_statistic_category=large_statistic_category
                        )
                        .distinct()
                        .values_list("medium_statistic_category", flat=True)
                    )
                    tasks = not_null_tasks.filter(
                        Q(
                            categories__large_statistic_category=large_statistic_category
                        )
                        & ~Q(
                            categories__medium_statistic_category__in=medium_category_ids
                        )
                        & Q(organization=organization)
                    )
                    schedules = not_null_schedules.filter(
                        Q(
                            categories__large_statistic_category=large_statistic_category
                        )
                        & ~Q(
                            categories__medium_statistic_category__in=medium_category_ids
                        )
                        & Q(organization=organization)
                    )
                    if tasks.exists():
                        for task in tasks:
                            task.categories.update(
                                medium_statistic_category=None
                            )
                    if schedules.exists():
                        for schedule in schedules:
                            schedule.categories.update(
                                medium_statistic_category=None
                            )
                    for medium in medium_category_ids:
                        small_category_ids = (
                            organization.organizations_statistic_categories.filter(
                                large_statistic_category=large_statistic_category,
                                medium_statistic_category=medium,
                            )
                            .distinct()
                            .values_list("small_statistic_category", flat=True)
                        )
                        tasks = not_null_tasks.filter(
                            Q(
                                categories__large_statistic_category=large_statistic_category
                            )
                            & Q(categories__medium_statistic_category=medium)
                            & ~Q(
                                categories__small_statistic_category__in=small_category_ids
                            )
                            & Q(organization=organization)
                        )
                        schedules = not_null_schedules.filter(
                            Q(
                                categories__large_statistic_category=large_statistic_category
                            )
                            & Q(categories__medium_statistic_category=medium)
                            & ~Q(
                                categories__small_statistic_category__in=small_category_ids
                            )
                            & Q(organization=organization)
                        )
                        if tasks.exists():
                            for task in tasks:
                                task.categories.update(
                                    small_statistic_category=None
                                )
                        if schedules.exists():
                            for schedule in schedules:
                                schedule.categories.update(
                                    small_statistic_category=None
                                )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0012_organization_hierarchize_at"),
    ]

    operations = [
        migrations.RunPython(
            clear_task_category_not_in_category_hierarchy,
            migrations.RunPython.noop,
        ),
    ]
