# Generated by Django 5.0.6 on 2025-04-21 17:03

from django.db import migrations, models
from users.constants import AvatarColors


def seed_icon_color_to_organizations(apps, schema_editor):
    """
    Seed icon color to organizations.
    """
    Organization = apps.get_model("organizations", "Organization")
    for organization in Organization.objects.all():
        organization.icon_color = AvatarColors.random()
        organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_clear_task_category_not_in_category_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="icon_color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            seed_icon_color_to_organizations, migrations.RunPython.noop
        ),
    ]
