# Generated by Django 5.0.6 on 2025-05-28 17:27
import uuid

from django.db import migrations, models

from organizations.constants import OrganizationTypes
from users.constants import AvatarColors


def seed_default_organization_calendar(apps, schema_editor):
    """
    Seed icon color to organizations.
    """
    Company = apps.get_model("companies", "Company")
    for company in Company.objects.all():
        organization, _ = company.organizations.get_or_create(
            type=OrganizationTypes.CALENDAR.value,
            defaults={
                "name": "カレンダーカテゴリー",
                "uuid": uuid.uuid4(),
                "icon_color": AvatarColors.random(),
            },
        )
        organization.users.all().delete()
        for user in company.users.all():
            organization.users.add(user, through_defaults={"company": company})


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0015_remove_organization_skills_step_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "NORMAL"),
                    ("PROJECT", "PROJECT"),
                    ("CALENDAR", "CALENDAR"),
                ],
                default="NORMAL",
                max_length=50,
            ),
        ),
        migrations.RunPython(
            seed_default_organization_calendar, migrations.RunPython.noop
        ),
    ]
