# Generated by Django 5.0.6 on 2025-05-28 17:27
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0015_remove_organization_skills_step_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "NORMAL"),
                    ("PROJECT", "PROJECT"),
                    ("CALENDAR", "CALENDAR"),
                ],
                default="NORMAL",
                max_length=50,
            ),
        ),
    ]
