# Generated by Django 5.0.6 on 2025-07-03 16:18

from django.db import migrations

from organizations.constants import (
    OrganizationTypes,
    CALENDAR_ORGANIZATION_NAME,
)
from users.constants import AvatarColors


def seed_default_organization_calendar(apps, schema_editor):
    """
    Seed calendar organization for each company.
    """
    Company = apps.get_model("companies", "Company")
    Organization = apps.get_model("organizations", "Organization")

    for company in Company.objects.all():
        organization, _ = Organization.objects.update_or_create(
            company=company,
            type=OrganizationTypes.CALENDAR.value,
            defaults={
                "name": CALENDAR_ORGANIZATION_NAME,
                "icon_color": AvatarColors.random(),
            },
        )
        for user in company.users.all():
            organization.users.add(user, through_defaults={"company": company})


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_alter_organization_type"),
    ]

    operations = [
        migrations.RunPython(
            seed_default_organization_calendar, migrations.RunPython.noop
        ),
    ]
