# Generated by Django 5.0.6 on 2025-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_seed_default_organization_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsstatisticcategories",
            name="deleted_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LARGE", "LARGE"),
                    ("MEDIUM", "MEDIUM"),
                    ("SMALL", "SMALL"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
