# Generated by Django 5.0.6 on 2024-11-28 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("organizations", "0005_rename_level_organizationsskills_levels"),
        ("skills", "0004_remove_skillmap_large_statistic_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitLevelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level_before_submit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("レベル0", "LEVEL_0"),
                            ("レベル1", "LEVEL_1"),
                            ("レベル2", "LEVEL_2"),
                            ("レベル3", "LEVEL_3"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "level_after_submit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("レベル0", "LEVEL_0"),
                            ("レベル1", "LEVEL_1"),
                            ("レベル2", "LEVEL_2"),
                            ("レベル3", "LEVEL_3"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("申請中", "APPLYING"),
                            ("承認", "APPROVE"),
                            ("却下", "REJECT"),
                        ],
                        default="申請中",
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submit_level_histories",
                        to="companies.company",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submit_level_histories",
                        to="organizations.organization",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submit_level_histories",
                        to="skills.skill",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submit_level_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
