# Generated by Django 5.0.6 on 2025-01-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0005_alter_skillmap_skill"),
        ("submit_levels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitlevelhistory",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submit_level_histories",
                to="skills.skill",
            ),
        ),
    ]
