# Generated by Django 5.0.6 on 2025-05-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0009_remove_skillmap_index_remove_skillmap_level_and_more"),
        ("submit_levels", "0002_alter_submitlevelhistory_skill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submitlevelhistory",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_submit_levels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submitlevelhistory",
            name="items",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submitlevelhistory",
            name="step_after_submit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ステップ1", "STEP_1"),
                    ("ステップ2", "STEP_2"),
                    ("ステップ3", "STEP_3"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submitlevelhistory",
            name="step_before_submit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ステップ1", "STEP_1"),
                    ("ステップ2", "STEP_2"),
                    ("ステップ3", "STEP_3"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submitlevelhistory",
            name="level_after_submit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("レベル1", "LEVEL_1"),
                    ("レベル2", "LEVEL_2"),
                    ("レベル3", "LEVEL_3"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submitlevelhistory",
            name="level_before_submit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("レベル1", "LEVEL_1"),
                    ("レベル2", "LEVEL_2"),
                    ("レベル3", "LEVEL_3"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submitlevelhistory",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submit_level_histories",
                to="skills.skill",
            ),
        ),
    ]
