# Generated by Django 5.0.6 on 2025-05-13 11:13

from django.db import migrations


def clear_data_skill(apps, schema_editor):
    """
    Handle clear data skill not have organization
    """
    SubmitLevelHistory = apps.get_model("submit_levels", "SubmitLevelHistory")
    SubmitLevelHistory.objects.filter(skill__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "submit_levels",
            "0003_submitlevelhistory_approver_submitlevelhistory_items_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(clear_data_skill, migrations.RunPython.noop),
    ]
