# Generated by Django 5.0.6 on 2025-05-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit_levels", "0004_clear_old_data_submit_levels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submitlevelhistory",
            name="items",
        ),
        migrations.AlterField(
            model_name="submitlevelhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("申請中", "APPLYING"),
                    ("承認", "APPROVE"),
                    ("却下", "REJECT"),
                    ("ドラフト", "DRAFT"),
                ],
                default="申請中",
                max_length=50,
            ),
        ),
    ]
