# Generated by Django 5.0.6 on 2024-11-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="skills.statisticcategory",
            ),
        ),
    ]
