# Generated by Django 5.0.6 on 2024-12-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_initial"),
        ("skills", "0004_remove_skillmap_large_statistic_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="statistic_category",
        ),
        migrations.RemoveField(
            model_name="category",
            name="type",
        ),
        migrations.AddField(
            model_name="category",
            name="large_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="large_categories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="medium_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medium_categories",
                to="skills.statisticcategory",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="small_statistic_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="small_categories",
                to="skills.statisticcategory",
            ),
        ),
    ]
