# Generated by Django 5.0.6 on 2025-09-08 19:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_company_is_show_holidays_calendar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField()),
                (
                    "item_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("帽子", "HAT"),
                            ("服装", "CLOTHES"),
                            ("靴", "SHOES"),
                            ("背景", "BACKGROUND"),
                        ],
                        null=True,
                    ),
                ),
                ("price", models.IntegerField()),
                ("color", models.CharField()),
                (
                    "type_price",
                    models.CharField(
                        blank=True,
                        choices=[("COIN", "COIN"), ("PEARL", "PEARL")],
                        null=True,
                    ),
                ),
                (
                    "crop_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="items/crop_items",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "full_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="items/full_items",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                ]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("帽子", "HAT"),
                            ("服装", "CLOTHES"),
                            ("靴", "SHOES"),
                            ("背景", "BACKGROUND"),
                        ],
                        null=True,
                    ),
                ),
                ("is_weared", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_items",
                        to="companies.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_items",
                        to="shop_items.shopitems",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
