# Generated by Django 5.0.6 on 2025-09-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_items", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useritems",
            old_name="is_weared",
            new_name="is_equipped",
        ),
    ]
