# Generated by Django 5.0.6 on 2025-09-17 12:13

from django.db import migrations, models
from shop_items.constants import ItemDefaultEnums, ItemTypes
from shop_items.management.commands.seed_data_shop_items import (
    seed_shop_items_data,
)


def generate_unique_key(apps, schema_editor):
    ShopItems = apps.get_model("shop_items", "ShopItems")

    # Map ItemTypes to ItemDefaultEnums
    item_type_enum_map = {
        ItemTypes.HAT.value: ItemDefaultEnums.HAT.value,
        ItemTypes.CLOTHES.value: ItemDefaultEnums.CLOTHES.value,
        ItemTypes.SHOES.value: ItemDefaultEnums.SHOES.value,
    }

    for type, data in item_type_enum_map.items():
        items = ShopItems.objects.filter(item_type=type).order_by("id")
        for idx, item in enumerate(items):
            item.key = data[idx]["key"]
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("shop_items", "0002_rename_is_weared_useritems_is_equipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitems",
            name="key",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.RunPython(
            generate_unique_key, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="shopitems",
            name="key",
            field=models.CharField(max_length=255, null=False, unique=True),
        ),
        migrations.RunPython(seed_shop_items_data, migrations.RunPython.noop),
    ]
