# Generated by Django 5.1.15 on 2025-12-10 18:26

from django.db import migrations

from shop_items.management.commands.seed_data_shop_items import (
    seed_shop_items_data,
)


class Migration(migrations.Migration):

    dependencies = [
        ("shop_items", "0003_shopitems_key"),
    ]

    operations = [
        migrations.RunPython(seed_shop_items_data, migrations.RunPython.noop),
    ]
