# Generated by Django 5.0.6 on 2024-11-14 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendars", "0001_initial"),
        ("companies", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsschedules",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="participants",
            field=models.ManyToManyField(
                related_name="schedules",
                through="calendars.ParticipantsSchedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participantsschedules",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_schedules",
                to="calendars.schedule",
            ),
        ),
        migrations.AddField(
            model_name="tagsschedules",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags_schedules",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="tagsschedules",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags_schedules",
                to="calendars.schedule",
            ),
        ),
        migrations.AddField(
            model_name="tagsschedules",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags_schedules",
                to="tags.tag",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="tags",
            field=models.ManyToManyField(
                related_name="schedules",
                through="calendars.TagsSchedules",
                to="tags.tag",
            ),
        ),
    ]
