# Generated by Django 5.0.6 on 2024-12-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0002_initial"),
        ("organizations", "0005_rename_level_organizationsskills_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
