# Generated by Django 5.0.6 on 2025-04-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0003_schedule_organization"),
        ("organizations", "0011_organization_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="organizations.organization",
            ),
        ),
    ]
