# Generated by Django 5.0.6 on 2025-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0004_alter_schedule_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="select_organizations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
