# Generated by Django 5.0.6 on 2025-04-22 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0005_schedule_select_organizations"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="start_date",
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RepeatSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("plan_start_date", models.DateTimeField()),
                ("plan_end_date", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_schedules",
                        to="companies.company",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_schedules",
                        to="calendars.schedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
