# Generated by Django 5.0.6 on 2025-04-22 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_data_repeat_schedules(apps, schema_editor):
    """
    Move start date and end date from schedule to repeat schedule
    """
    Schedule = apps.get_model("calendars", "Schedule")
    RepeatSchedule = apps.get_model("calendars", "RepeatSchedule")
    for schedule in Schedule.objects.all():
        schedule.recurring = {
            "month": None,
            "week_day": None,
            "month_day": None,
            "repeat_type": "ONCE",
            "plan_end_date": schedule.end_date.isoformat(),
            "plan_start_date": schedule.start_date.isoformat(),
            "repeat_interval": None,
        }
        schedule.save()
        RepeatSchedule.objects.create(
            schedule=schedule,
            company=schedule.company,
            plan_start_date=schedule.start_date,
            plan_end_date=schedule.end_date,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0005_schedule_select_organizations"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="recurring",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RepeatSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("plan_start_date", models.DateTimeField()),
                ("plan_end_date", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_schedules",
                        to="companies.company",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_schedules",
                        to="calendars.schedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            seed_data_repeat_schedules, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="start_date",
        ),
    ]
