# Generated by Django 5.0.6 on 2025-05-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0007_eventlocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="address",
        ),
        migrations.AddField(
            model_name="schedule",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="calendars.eventlocation",
            ),
        ),
    ]
