# Generated by Django 5.0.6 on 2025-05-30 15:52

from django.db import migrations

from organizations.constants import OrganizationTypes


def seed_default_calendar_organization(apps, schema_editor):
    """
    Set default calendar organization for schedule
    """
    Schedule = apps.get_model("calendars", "Schedule")
    for schedule in Schedule.objects.all():
        company = schedule.company
        calendar_organization = company.organizations.filter(
            type=OrganizationTypes.CALENDAR.value
        ).first()
        schedule.organization = calendar_organization
        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0008_remove_schedule_address_schedule_location"),
    ]

    operations = [
        migrations.RunPython(
            seed_default_calendar_organization, migrations.RunPython.noop
        ),
    ]
