# Generated by Django 5.0.6 on 2025-06-20 13:38

from django.db import migrations

from organizations.constants import OrganizationTypes


def seed_default_calendar_organization(apps, schema_editor):
    """
    Set default calendar organization for schedule
    """
    Schedule = apps.get_model("calendars", "Schedule")
    for schedule in Schedule.objects.all():
        company = schedule.company
        calendar_organization = company.organizations.filter(
            type=OrganizationTypes.CALENDAR.value
        ).first()
        schedule.organization = calendar_organization
        for tag in schedule.tags.all():
            if not calendar_organization.organization_tags.filter(
                tag=tag
            ).exists():
                schedule.tags.remove(tag)
        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0009_seed_default_calendar_organization"),
    ]

    operations = [
        migrations.RunPython(
            seed_default_calendar_organization, migrations.RunPython.noop
        ),
    ]
