# Generated by Django 5.0.6 on 2025-07-24 19:38

import django.db.models.deletion
from django.db import migrations, models

from calendars.constants import ScheduleRepeatOption
from tasks.constants import FrequencyMap


def seed_recurring_option(apps, schema_editor):
    """
    Seed recurring option
    """
    Schedule = apps.get_model("calendars", "Schedule")
    for schedule in Schedule.objects.all():
        if schedule.recurring["repeat_type"] != FrequencyMap.ONCE.value:
            schedule.recurring_option = (
                ScheduleRepeatOption.THIS_AND_FOLLOWING_EVENTS.value
            )
        else:
            schedule.recurring_option = ScheduleRepeatOption.THIS_EVENT.value
        schedule.save()


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0010_seed_calendar_org_and_remove_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_schedules",
                to="calendars.schedule",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("THIS_EVENT", "THIS_EVENT"),
                    ("THIS_AND_FOLLOWING_EVENTS", "THIS_AND_FOLLOWING_EVENTS"),
                    ("ALL_EVENTS", "ALL_EVENTS"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.RunPython(seed_recurring_option, migrations.RunPython.noop),
    ]
