# Generated by Django 5.0.6 on 2024-12-17 13:55

import uuid
from django.db import migrations, models


def generate_unique_uuid(apps, schema_editor):
    TaskDuration = apps.get_model("tasks", "TaskDuration")
    for task in TaskDuration.objects.all():
        task.uuid = uuid.uuid4()
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskduration",
            name="uuid",
            field=models.UUIDField(unique=True, null=True),
        ),
        migrations.RunPython(generate_unique_uuid),
        migrations.AlterField(
            model_name="taskduration",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False),
        ),
    ]
