# Generated by Django 5.0.6 on 2024-12-18 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskduration_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskduration",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
