# Generated by Django 5.0.6 on 2024-12-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_rename_level_organizationsskills_levels"),
        ("tasks", "0004_alter_taskduration_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="actual_end_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="actual_start_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="plan_end_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="plan_start_date",
        ),
        migrations.AddField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
