# Generated by Django 5.0.6 on 2024-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_actual_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("一般タスク", "GENERAL_TASK"),
                    ("管理タスク", "MANAGEMENT_TASK"),
                    ("専任タスク", "SPECIALIZED_TASK"),
                    ("その他", "OTHER_TASK"),
                    ("マイテンプレート", "MY_TEMPLATE"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
