# Generated by Django 5.0.6 on 2024-12-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_rename_level_organizationsskills_levels"),
        ("tasks", "0006_alter_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="organizations.organization",
            ),
        ),
    ]
