# Generated by Django 5.0.6 on 2025-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskduration",
            name="is_cancel_alert",
            field=models.BooleanField(default=False),
        ),
    ]
