# Generated by Django 5.0.6 on 2025-02-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_taskduration_is_cancel_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="remind_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
