# Generated by Django 5.0.6 on 2025-02-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminds",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
