# Generated by Django 5.0.6 on 2025-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_task_reminds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="priority",
        ),
        migrations.AddField(
            model_name="task",
            name="recurring",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
