# Generated by Django 5.0.6 on 2025-03-25 16:24

import random
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from tasks.constants import (
    INITIAL_INDEX_VALUE,
    TaskStatus as TaskStatusEnum,
    TaskTypes,
)


def update_index_for_team(apps, schema_editor):
    """
    Update index for task team
    """
    FAKE_ORG_NAME = "ダミーチーム"
    Company = apps.get_model("companies", "Company")
    Organization = apps.get_model("organizations", "Organization")
    Task = apps.get_model("tasks", "Task")
    TeamTaskIndex = apps.get_model("tasks", "TeamTaskIndex")
    TaskStatus = apps.get_model("tasks", "TaskStatus")

    statuses = TaskStatus.objects.exclude(
        name=TaskStatusEnum.MY_ROUTINE.value
    ).order_by("id")

    # Ensure each task is assigned to one user and one organization
    for task in (
        Task.objects.select_related("organization", "company")
        .prefetch_related("people_in_charge")
        .all()
    ):
        company = task.company
        people = list(task.people_in_charge.all())
        organizations = list(company.organizations.all())

        if len(people) > 1:
            # Keep only the first person in charge
            task.people_in_charge.set(
                [people[0]], through_defaults={"company": company}
            )
        elif not people:
            # Get all users in the company
            users = list(company.users.all())
            users_with_org = [
                user for user in users if user.organizations.exists()
            ]

            if users_with_org:
                # Pick a random user that has an organization
                random_user = random.choice(users_with_org)
                org = random_user.organizations.first()
            elif users:
                # Pick a random user without an organization and create a temporary organization
                random_user = random.choice(users)
                org = random.choice(organizations)
                if not org:
                    org = Organization.objects.create(
                        name=FAKE_ORG_NAME, company=company
                    )

                random_user.organizations.add(
                    org, through_defaults={"company": company}
                )
            else:
                continue

            # Assign the user and organization to the task
            task.people_in_charge.set(
                [random_user], through_defaults={"company": company}
            )
            task.organization = org
            task.save(update_fields=["organization"])

        # Ensure the task has an organization
        if not task.organization and people:
            org = people[0].organizations.first()

            # If not org then get or create new org
            if not org:
                org = random.choice(organizations)
                if not org:
                    org = Organization.objects.get_or_create(
                        name=FAKE_ORG_NAME, company=company
                    )
                people[0].organizations.add(
                    org, through_defaults={"company": company}
                )
            task.organization = org
            task.save(update_fields=["organization"])

    # Migrate data index default for team tasks
    for company in Company.objects.prefetch_related("organizations").all():
        for org in company.organizations.prefetch_related("users").all():
            for user in org.users.prefetch_related("in_charge_tasks").all():
                for status in statuses:
                    index = INITIAL_INDEX_VALUE
                    tasks = (
                        user.in_charge_tasks.filter(
                            status=status, organization=org
                        )
                        .exclude(type=TaskTypes.MY_TEMPLATE.value)
                        .order_by("deadline")
                    )

                    for task in tasks:
                        TeamTaskIndex.objects.update_or_create(
                            team=task.organization,
                            task=task,
                            company=task.company,
                            defaults={
                                "user": user,
                                "index": index,
                            },
                        )
                        index += 100


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("organizations", "0008_organizationsstatisticcategories_color"),
        ("tasks", "0012_remove_task_priority_task_recurring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamTaskIndex",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.FloatField()),
                ("pin_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_task_indexes",
                        to="companies.company",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_task_index",
                        to="tasks.task",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_task_index",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_task_index",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(update_index_for_team, migrations.RunPython.noop),
    ]
