# Generated by Django 5.0.6 on 2025-03-31 20:46

from django.db import migrations
from tasks.constants import (
    INITIAL_INDEX_VALUE,
    TaskStatus as TaskStatusEnum,
    TaskTypes,
)


def update_index_for_team(apps, schema_editor):
    """
    Update index for task team
    """
    FAKE_ORG_NAME = "ダミーチーム"
    Company = apps.get_model("companies", "Company")
    Organization = apps.get_model("organizations", "Organization")
    Task = apps.get_model("tasks", "Task")
    TeamTaskIndex = apps.get_model("tasks", "TeamTaskIndex")
    TaskStatus = apps.get_model("tasks", "TaskStatus")

    statuses = TaskStatus.objects.exclude(
        name=TaskStatusEnum.MY_ROUTINE.value
    ).order_by("id")

    # Ensure each task is assigned to one user and one organization
    for task in (
        Task.objects.select_related("organization", "company")
        .prefetch_related("people_in_charge")
        .all()
    ):
        company = task.company
        people = list(task.people_in_charge.all())
        first_org = company.organizations.first()

        if len(people) > 1:
            # Keep only the first person in charge
            task.people_in_charge.set(
                [people[0]], through_defaults={"company": company}
            )

        # Ensure the task has an organization
        if not task.organization and people:
            org = people[0].organizations.first()

            # If not org then get or create new org
            if not org:
                if first_org:
                    org = first_org
                else:
                    org, _ = Organization.objects.get_or_create(
                        name=FAKE_ORG_NAME, company=company
                    )
                people[0].organizations.add(
                    org, through_defaults={"company": company}
                )
            task.organization = org
            task.save(update_fields=["organization"])

    # Migrate data index default for team tasks
    for company in Company.objects.prefetch_related("organizations").all():
        for org in company.organizations.prefetch_related("users").all():
            for user in org.users.prefetch_related("in_charge_tasks").all():
                for status in statuses:
                    index = INITIAL_INDEX_VALUE
                    tasks = (
                        user.in_charge_tasks.filter(
                            status=status, organization=org
                        )
                        .exclude(type=TaskTypes.MY_TEMPLATE.value)
                        .order_by("deadline")
                    )

                    for task in tasks:
                        TeamTaskIndex.objects.update_or_create(
                            team=task.organization,
                            task=task,
                            company=task.company,
                            defaults={
                                "user": user,
                                "index": index,
                            },
                        )
                        index += 100


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_teamtaskindex"),
    ]

    operations = [
        migrations.RunPython(update_index_for_team, migrations.RunPython.noop),
    ]
