# Generated by Django 5.0.6 on 2025-04-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_seed_user_to_task_durations"),
    ]

    operations = []
