# Generated by Django 5.0.6 on 2025-05-06 16:20

from django.db import migrations


def reset_team_task_index(apps, schema_editor):
    """
    Reset team task index
    """
    TeamTaskIndex = apps.get_model("tasks", "TeamTaskIndex")

    TeamTaskIndex.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_clear_data_team_task_index"),
    ]

    operations = [
        migrations.RunPython(reset_team_task_index, migrations.RunPython.noop)
    ]
