# Generated by Django 5.0.6 on 2025-07-07 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0010_seed_calendar_org_and_remove_tag"),
        ("companies", "0002_company_is_show_holidays_calendar"),
        ("tasks", "0019_reset_index_team_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskduration",
            index=models.Index(
                fields=["started_at", "paused_at"],
                name="tasks_taskd_started_796d43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskduration",
            index=models.Index(
                fields=["task"], name="tasks_taskd_task_id_11bf6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskduration",
            index=models.Index(
                fields=["schedule"], name="tasks_taskd_schedul_ae0b50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskduration",
            index=models.Index(
                fields=["user"], name="tasks_taskd_user_id_5ff9f0_idx"
            ),
        ),
    ]
