# Generated by Django 5.0.6 on 2025-08-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_taskduration_tasks_taskd_started_796d43_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskFrequent",
        ),
    ]
