# Generated by Django 5.0.6 on 2025-10-15 12:49

from django.db import migrations, models

from tasks.constants import TaskStatus


def seed_archive_task(apps, schema_editor):
    """
    Seed archive task
    """
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.filter(
        status_name=TaskStatus.COMPLETED.value
    ).all():
        task.completed_at = task.updated_at
        task.save(update_fields=["completed_at"])
        for user in task.people_in_charge.all():
            task_completes = Task.objects.filter(
                people_in_charge=user,
                completed_at__isnull=False,
                is_archived=False,
            ).order_by("-completed_at")
            if task_completes.count() > 10:
                old_task_completed = task_completes.first()
                old_task_completed.is_archived = True
                old_task_completed.save(update_fields=["is_archived"])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_delete_taskfrequent"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_archive_task, migrations.RunPython.noop),
    ]
