# Generated by Django 5.0.6 on 2025-10-21 11:55

from datetime import datetime
import random
from django.db import migrations, models
from django.utils.timezone import timedelta


def seed_archived_time(apps, schema_editor):
    """
    Seed task duration by user
    """
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.filter(is_archived=True).all():
        # Generate a random number of days
        random_days = random.randint(0, 30)
        direction = random.choice([-1, 1])
        random_date = datetime.now() + timedelta(days=direction * random_days)
        task.archived_at = random_date
        task.save(update_fields=["archived_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0022_task_completed_at_task_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(seed_archived_time, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="task",
            name="is_archived",
        ),
    ]
