# Generated by Django 5.1.15 on 2026-02-12 16:52

from django.db import migrations
from django.db.models import F
from django.utils import timezone

from tasks.constants import TaskStatus


def update_completed_at(apps, schema_editor):
    """
    Update completed_at for completed tasks with null completed_at
    and keep only 10 most recent completed tasks per user (archive the rest)
    """
    Task = apps.get_model("tasks", "Task")
    PeopleInChargeTasks = apps.get_model("tasks", "PeopleInChargeTasks")

    # Update completed_at for completed tasks with null completed_at
    Task.objects.filter(
        status__name=TaskStatus.COMPLETED.value,
    ).update(status_name=TaskStatus.COMPLETED.value)
    Task.objects.filter(
        status_name=TaskStatus.COMPLETED.value,
        completed_at__isnull=True,
    ).update(completed_at=F("updated_at"))

    #  Archive completed tasks beyond 10 per user
    current_time = timezone.now()

    # Get all users who have tasks assigned to them
    users_with_tasks = PeopleInChargeTasks.objects.values_list(
        "user_id", flat=True
    ).distinct()

    for user_id in users_with_tasks:
        # Get all completed, non-archived tasks for this user, ordered by completion date (newest first)
        completed_tasks = (
            Task.objects.filter(
                people_in_charge__id=user_id,
                status_name=TaskStatus.COMPLETED.value,
                completed_at__isnull=False,
                archived_at__isnull=True,
            )
            .order_by("-completed_at")
            .values_list("id", flat=True)
        )

        # Get IDs of tasks to archive (beyond the first 10)
        task_ids_to_archive = list(completed_tasks)[10:]

        # Bulk update all tasks that need to be archived
        if task_ids_to_archive:
            Task.objects.filter(id__in=task_ids_to_archive).update(
                archived_at=current_time
            )


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0023_remove_task_is_archived_task_archived_at"),
    ]

    operations = [
        migrations.RunPython(update_completed_at, migrations.RunPython.noop),
    ]
